package com.g20.CPEN431.A7.network;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.List;

// -----------------------------------------------------------------------------
// AI-GENERATED CODE ACKNOWLEDGEMENT
// -----------------------------------------------------------------------------
// Code generated by: Claude Opus (Anthropic, PBC)
//
// This code was AI-assisted and has been reviewed for accuracy and
// suitability for its intended purpose.
// -----------------------------------------------------------------------------

/**
 * Internal gossip message format for push-pull protocol.
 *
 * Binary format:
 *   [1 byte: message type]
 *   [4 bytes: sender node id]
 *   [4 bytes: number of entries]
 *   For each entry:
 *     [4 bytes: node id]
 *     [4 bytes: IP address (as int)]
 *     [4 bytes: port]
 *     [8 bytes: heartbeat counter]
 *     [1 byte: alive flag (1 = alive, 0 = dead)]
 *
 * Total per entry: 21 bytes
 * Header: 9 bytes
 */
public class GossipMessage {

    // Message types
    public static final byte TYPE_PUSH = 0x01;
    public static final byte TYPE_PULL_REQUEST = 0x02;
    public static final byte TYPE_PULL_RESPONSE = 0x03;
    public static final byte TYPE_PUSH_PULL = 0x04; // Combined push + pull request

    // Magic bytes to distinguish gossip from client messages
    // We'll use a specific prefix in the UDP payload
    public static final byte[] GOSSIP_MAGIC = new byte[]{(byte) 0xDE, (byte) 0x55, (byte) 0x1E, (byte) 0xAA};

    private static final int HEADER_SIZE = 1 + 4 + 4; // type + senderId + entryCount
    private static final int ENTRY_SIZE = 4 + 4 + 4 + 8 + 1; // id + ip + port + heartbeat + alive
    private static final int MAGIC_SIZE = 4;

    private byte messageType;
    private int senderId;
    private List<GossipEntry> entries;

    public GossipMessage(byte messageType, int senderId) {
        this.messageType = messageType;
        this.senderId = senderId;
        this.entries = new ArrayList<>();
    }

    public byte getMessageType() {
        return messageType;
    }

    public int getSenderId() {
        return senderId;
    }

    public List<GossipEntry> getEntries() {
        return entries;
    }

    public void addEntry(int nodeId, int ipAsInt, int port, long heartbeatCounter, boolean alive) {
        entries.add(new GossipEntry(nodeId, ipAsInt, port, heartbeatCounter, alive));
    }

    /**
     * Serialize to bytes with magic prefix.
     */
    public byte[] serialize() {
        int size = MAGIC_SIZE + HEADER_SIZE + entries.size() * ENTRY_SIZE;
        ByteBuffer buffer = ByteBuffer.allocate(size);

        // Magic prefix
        buffer.put(GOSSIP_MAGIC);

        // Header
        buffer.put(messageType);
        buffer.putInt(senderId);
        buffer.putInt(entries.size());

        // Entries
        for (GossipEntry entry : entries) {
            buffer.putInt(entry.nodeId);
            buffer.putInt(entry.ipAsInt);
            buffer.putInt(entry.port);
            buffer.putLong(entry.heartbeatCounter);
            buffer.put(entry.alive ? (byte) 1 : (byte) 0);
        }

        return buffer.array();
    }

    /**
     * Check if a byte array starts with the gossip magic prefix.
     */
    public static boolean isGossipMessage(byte[] data, int length) {
        if (length < MAGIC_SIZE) return false;
        return data[0] == GOSSIP_MAGIC[0]
                && data[1] == GOSSIP_MAGIC[1]
                && data[2] == GOSSIP_MAGIC[2]
                && data[3] == GOSSIP_MAGIC[3];
    }

    /**
     * Deserialize from bytes (including magic prefix).
     */
    public static GossipMessage deserialize(byte[] data, int length) {
        if (length < MAGIC_SIZE + HEADER_SIZE) {
            return null;
        }

        ByteBuffer buffer = ByteBuffer.wrap(data, 0, length);

        // Skip magic
        buffer.position(MAGIC_SIZE);

        byte type = buffer.get();
        int senderId = buffer.getInt();
        int entryCount = buffer.getInt();

        GossipMessage msg = new GossipMessage(type, senderId);

        for (int i = 0; i < entryCount; i++) {
            if (buffer.remaining() < ENTRY_SIZE) break;
            int nodeId = buffer.getInt();
            int ipAsInt = buffer.getInt();
            int port = buffer.getInt();
            long heartbeat = buffer.getLong();
            boolean alive = buffer.get() == 1;
            msg.addEntry(nodeId, ipAsInt, port, heartbeat, alive);
        }

        return msg;
    }

    /**
     * Convert an InetAddress to int.
     */
    public static int ipToInt(java.net.InetAddress addr) {
        byte[] bytes = addr.getAddress();
        return ((bytes[0] & 0xFF) << 24)
                | ((bytes[1] & 0xFF) << 16)
                | ((bytes[2] & 0xFF) << 8)
                | (bytes[3] & 0xFF);
    }

    /**
     * Convert int back to InetAddress.
     */
    public static java.net.InetAddress intToIp(int ip) {
        try {
            byte[] bytes = new byte[]{
                    (byte) (ip >>> 24),
                    (byte) (ip >>> 16),
                    (byte) (ip >>> 8),
                    (byte) ip
            };
            return java.net.InetAddress.getByAddress(bytes);
        } catch (java.net.UnknownHostException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * An entry in the gossip membership list.
     */
    public static class GossipEntry {
        public final int nodeId;
        public final int ipAsInt;
        public final int port;
        public final long heartbeatCounter;
        public final boolean alive;

        public GossipEntry(int nodeId, int ipAsInt, int port, long heartbeatCounter, boolean alive) {
            this.nodeId = nodeId;
            this.ipAsInt = ipAsInt;
            this.port = port;
            this.heartbeatCounter = heartbeatCounter;
            this.alive = alive;
        }
    }
}