package com.g20.CPEN431.A9.storage;

import com.g20.CPEN431.A9.network.Node;

import com.google.protobuf.ByteString;

import java.nio.ByteBuffer;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.locks.ReadWriteLock;
import java.util.concurrent.locks.ReentrantReadWriteLock;
import java.util.Set;


// -----------------------------------------------------------------------------
// AI-GENERATED CODE ACKNOWLEDGEMENT
// -----------------------------------------------------------------------------
// Code generated by: Claude Opus (Anthropic, PBC)
//
// This code was AI-assisted and has been reviewed for accuracy and
// suitability for its intended purpose.
// -----------------------------------------------------------------------------
public class ConsistentHashmap {

    // The hash ring: maps hash values to nodes
    private final TreeMap<Integer, Node> ring = new TreeMap<>();

    // Read-write lock: concurrent reads, exclusive writes
    private final ReadWriteLock lock = new ReentrantReadWriteLock();

    // Number of virtual nodes per physical node (improves distribution)
    private final int virtualNodes;

    public ConsistentHashmap() {
        this(1); // Default: no virtual nodes
    }

    public ConsistentHashmap(int virtualNodes) {
        this.virtualNodes = virtualNodes;
    }

    /**
     * Add a node to the hash ring.
     * @return 0 on success (at least one virtual node added),
     *         1 if the node already exists (all vnodes are already present),
     *         2 if all virtual nodes collided with different nodes (none added)
     * Tolerates partial collisions: adds whichever virtual nodes don't collide.
     */
    public int addNode(Node node) {
        // Pre-compute hashes outside the lock
        int[] hashes = new int[virtualNodes];
        for (int i = 0; i < virtualNodes; i++) {
            hashes[i] = hash(node.id + "-" + i);
        }

        lock.writeLock().lock();
        try {
            int alreadyPresent = 0;
            int collisions = 0;
            int added = 0;

            for (int h : hashes) {
                Node existing = ring.get(h);
                if (existing != null) {
                    if (existing.id == node.id) {
                        alreadyPresent++;
                    } else {
                        collisions++;
                    }
                } else {
                    ring.put(h, node);
                    added++;
                }
            }

            if (alreadyPresent == virtualNodes) {
                return 1; // Node already fully present
            }
            if (added == 0) {
                return 2; // All slots collided, nothing added
            }
            return 0; // At least one vnode was added
        } finally {
            lock.writeLock().unlock();
        }
    }

    /**
     * Remove a node from the hash ring.
     * @return 0 on success (at least one virtual node removed),
     *         1 if the node was not found on the ring
     * Tolerates partial presence: removes whichever virtual nodes belong to this node.
     */
    public int removeNode(Node node) {
        // Pre-compute hashes outside the lock
        int[] hashes = new int[virtualNodes];
        for (int i = 0; i < virtualNodes; i++) {
            hashes[i] = hash(node.id + "-" + i);
        }

        lock.writeLock().lock();
        try {
            int removed = 0;
            for (int h : hashes) {
                Node existing = ring.get(h);
                if (existing != null && existing.id == node.id) {
                    ring.remove(h);
                    removed++;
                }
            }
            return removed > 0 ? 0 : 1;
        } finally {
            lock.writeLock().unlock();
        }
    }

    /**
     * Get the node responsible for the given key
     */
    public Node getNodeForKey(ByteString key) {
        int hash = hash(key.toByteArray());

        lock.readLock().lock();
        try {
            if (ring.isEmpty()) {
                return null;
            }

            // Find the first node clockwise from the hash
            Map.Entry<Integer, Node> entry = ring.ceilingEntry(hash);
            if (entry == null) {
                entry = ring.firstEntry();
            }
            return entry.getValue();
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Get all unique physical nodes in the ring
     */
    public Collection<Node> getAllNodes() {
        lock.readLock().lock();
        try {
            return new HashSet<>(ring.values());
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Get a random node from the ring
     * @return a random node, or null if the ring is empty
     */
    public Node getRandomNode() {
        lock.readLock().lock();
        try {
            if (ring.isEmpty()) {
                return null;
            }
            List<Node> nodes = new ArrayList<>(new HashSet<>(ring.values()));
            return nodes.get(ThreadLocalRandom.current().nextInt(nodes.size()));
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Check if ring is empty
     */
    public boolean isEmpty() {
        lock.readLock().lock();
        try {
            return ring.isEmpty();
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Get the number of unique physical nodes in the ring
     */
    public int size() {
        lock.readLock().lock();
        try {
            return new HashSet<>(ring.values()).size();
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Get the next clockwise node for a key that isn't the given node.
     * Used during recovery to find the successor (who held our keys while we were down).
     */
    public Node getSuccessorForKey(ByteString key, int selfId) {
        int h = hash(key.toByteArray());

        lock.readLock().lock();
        try {
            if (ring.isEmpty()) return null;

            Map.Entry<Integer, Node> entry = ring.ceilingEntry(h);
            if (entry == null) entry = ring.firstEntry();

            // Walk clockwise until we find a node that isn't self
            Integer startHash = entry.getKey();
            do {
                if (entry.getValue().id != selfId) {
                    return entry.getValue();
                }
                entry = ring.higherEntry(entry.getKey());
                if (entry == null) entry = ring.firstEntry();
            } while (!entry.getKey().equals(startHash));

            return null; // only self on ring
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Returns a snapshot (copy) of the ring under read lock.
     */
    public TreeMap<Integer, Node> getRingSnapshot() {
        lock.readLock().lock();
        try {
            return new TreeMap<>(ring);
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Lookup the responsible node for a key using a frozen ring snapshot.
     */
    public static Node getNodeForKeyFromSnapshot(byte[] keyBytes, TreeMap<Integer, Node> snapshot) {
        if (snapshot.isEmpty()) return null;
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] digest = md.digest(keyBytes);
            int hash = ByteBuffer.wrap(digest, 0, 4).getInt();
            Map.Entry<Integer, Node> entry = snapshot.ceilingEntry(hash);
            if (entry == null) entry = snapshot.firstEntry();
            return entry.getValue();
        } catch (java.security.NoSuchAlgorithmException e) {
            throw new RuntimeException("MD5 not available", e);
        }
    }

    /**
     * Get the set of node IDs that are immediate successors of the given node's
     * virtual positions. These are the nodes that absorbed the given node's keys
     * when it was down.
     */
    public Set<Integer> getSuccessorNodeIds(Node node) {
        lock.readLock().lock();
        try {
            Set<Integer> successors = new HashSet<>();
            for (int i = 0; i < virtualNodes; i++) {
                int h = hash(node.id + "-" + i);
                Map.Entry<Integer, Node> entry = ring.higherEntry(h);
                if (entry == null) entry = ring.firstEntry();
                if (entry == null) continue;

                // Walk clockwise until we find a different physical node
                Integer startKey = entry.getKey();
                do {
                    if (entry.getValue().id != node.id) {
                        successors.add(entry.getValue().id);
                        break;
                    }
                    entry = ring.higherEntry(entry.getKey());
                    if (entry == null) entry = ring.firstEntry();
                } while (!entry.getKey().equals(startKey));
            }
            return successors;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Get the set of node IDs that are immediate predecessors of the given node's
     * virtual positions. These are the nodes whose keys this node is responsible for
     * serving during recovery.
     */
    public Set<Integer> getPredecessorNodeIds(Node node) {
        lock.readLock().lock();
        try {
            Set<Integer> predecessors = new HashSet<>();
            for (int i = 0; i < virtualNodes; i++) {
                int h = hash(node.id + "-" + i);
                Map.Entry<Integer, Node> entry = ring.lowerEntry(h);
                if (entry == null) entry = ring.lastEntry();
                if (entry == null) continue;

                // Walk counter-clockwise until we find a different physical node
                Integer startKey = entry.getKey();
                do {
                    if (entry.getValue().id != node.id) {
                        predecessors.add(entry.getValue().id);
                        break;
                    }
                    entry = ring.lowerEntry(entry.getKey());
                    if (entry == null) entry = ring.lastEntry();
                } while (!entry.getKey().equals(startKey));
            }
            return predecessors;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Hash function using MD5
     */
    private int hash(String key) {
        return hash(key.getBytes());
    }

    private int hash(byte[] key) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] digest = md.digest(key);
            // Use first 4 bytes as integer
            return ByteBuffer.wrap(digest, 0, 4).getInt();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("MD5 not available", e);
        }
    }
}