package com.g20.CPEN431.A9.storage;

import com.g20.CPEN431.A9.Constants;

// -----------------------------------------------------------------------------
// AI-GENERATED CODE ACKNOWLEDGEMENT
// -----------------------------------------------------------------------------
// Code generated by: Claude Opus (Anthropic, PBC)
//
// This code was AI-assisted and has been reviewed for accuracy and
// suitability for its intended purpose.
// -----------------------------------------------------------------------------

import com.google.protobuf.ByteString;

import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

// This code was in part generated by an LLM.
public class KeyValueStore {
    private static volatile ConcurrentHashMap<ByteString, byte[]> store = new ConcurrentHashMap<>();
    private static final AtomicLong bytesUsed = new AtomicLong(0);

    // Memory cap for the store: total available memory minus memory used by queues, cache, JVM, etc.
    private static final long MEMORY_CAP = Runtime.getRuntime().maxMemory() - Constants.MEMORY_THRESHOLD_BYTES;

    // Estimated overhead per entry:
    // - ConcurrentHashMap.Node: ~48 bytes (object header, hash, pointers)
    // - ByteString key: ~24 bytes overhead + actual bytes
    // - byte[] value: ~20 bytes overhead + actual bytes
    private static final int ENTRY_OVERHEAD = 100;

    /**
     * Estimates the byte cost of storing a key-value entry.
     */
    private static long estimateEntrySize(int keySize, int valueSize) {
        // value storage includes 4 bytes for version
//        System.out.println("Memory Cap: " + MEMORY_CAP);
        return ENTRY_OVERHEAD + keySize + valueSize + 4;
    }

    /**
     * Checks if a new entry can be added without exceeding the memory cap.
     */
    public static boolean canAddEntry(int keySize, int valueSize) {
        long entrySize = estimateEntrySize(keySize, valueSize);
        return bytesUsed.get() + entrySize <= MEMORY_CAP;
    }

    /**
     * @return current estimated bytes used by the store
     */
    public static long getBytesUsed() {
        return bytesUsed.get();
    }

    /**
     * Converts version (int) and value (ByteString) to a single byte array.
     * Format: [4 bytes version (big-endian)] + [value bytes]
     */
    private static byte[] toBytes(int version, ByteString value) {
        byte[] valueBytes = value.toByteArray();
        byte[] combined = new byte[4 + valueBytes.length];
        // Store version as big-endian 4 bytes
        combined[0] = (byte) (version >> 24);
        combined[1] = (byte) (version >> 16);
        combined[2] = (byte) (version >> 8);
        combined[3] = (byte) version;
        // Copy value bytes
        System.arraycopy(valueBytes, 0, combined, 4, valueBytes.length);
        return combined;
    }

    /**
     * Converts a byte array back to a StoragePayload.
     */
    private static StoragePayload fromBytes(byte[] data) {
        if (data == null) {
            return null;
        }
        // Extract version from first 4 bytes (big-endian)
        int version = ((data[0] & 0xFF) << 24) |
                      ((data[1] & 0xFF) << 16) |
                      ((data[2] & 0xFF) << 8) |
                       (data[3] & 0xFF);
        // Extract value from remaining bytes
        ByteString value = ByteString.copyFrom(data, 4, data.length - 4);
        return new StoragePayload(value, version);
    }

    /**
     * @param key ByteString being the key.
     * @return StoragePayload or null if key does not exist
     */
    public static StoragePayload get(ByteString key) {
        return fromBytes(store.get(key));
    }

    public static StoragePayload put(ByteString key, ByteString value, int version) {
        byte[] newData = toBytes(version, value);
        byte[] oldData = store.put(key, newData);

        // Update bytes used: add new entry size
        long newEntrySize = estimateEntrySize(key.size(), value.size());
        if (oldData != null) {
            // Replace: subtract old value size, add new value size (key overhead unchanged)
            long oldValueSize = oldData.length;
            long newValueSize = newData.length;
            bytesUsed.addAndGet(newValueSize - oldValueSize);
        } else {
            // New entry: add full entry size
            bytesUsed.addAndGet(newEntrySize);
        }

        return fromBytes(oldData);
    }

    public static StoragePayload remove(ByteString key) {
        byte[] oldData = store.remove(key);
        if (oldData != null) {
            // Subtract full entry size (key overhead + value)
            long entrySize = estimateEntrySize(key.size(), oldData.length - 4);
            bytesUsed.addAndGet(-entrySize);
        }
        return fromBytes(oldData);
    }

    public static boolean containsKey(ByteString key) {
        return store.containsKey(key);
    }

    public static void clear() {
        store = new ConcurrentHashMap<>();
        bytesUsed.set(0);
    }

    /**
     * Expose the entry set for scanning (used by key transfer).
     */
    public static Set<Map.Entry<ByteString, byte[]>> entrySet() {
        return store.entrySet();
    }

    /**
     * Get raw byte[] (version+value) without parsing, for key transfer.
     */
    public static byte[] getRawBytes(ByteString key) {
        return store.get(key);
    }

    /**
     * Store raw bytes directly (version+value), with memory accounting.
     * Used by key transfer receiver.
     */
    public static void putRawBytes(ByteString key, byte[] rawData) {
        byte[] oldData = store.put(key, rawData);
        int valueSize = rawData.length - 4; // rawData = 4-byte version + value
        long newEntrySize = estimateEntrySize(key.size(), valueSize);
        if (oldData != null) {
            long oldValueSize = oldData.length;
            long newValueSize = rawData.length;
            bytesUsed.addAndGet(newValueSize - oldValueSize);
        } else {
            bytesUsed.addAndGet(newEntrySize);
        }
    }


    public static class StoragePayload {
        private final ByteString value;
        private final int version;

        StoragePayload(ByteString value, int version) {
            this.value = value;
            this.version = version;
        }

        public ByteString getValue() {
            return this.value;
        }

        public int getVersion() {
            return this.version;
        }
    }
}
