package com.g20.CPEN431.A9.network;

import com.g20.CPEN431.A9.storage.ConsistentHashmap;

// -----------------------------------------------------------------------------
// AI-GENERATED CODE ACKNOWLEDGEMENT
// -----------------------------------------------------------------------------
// Code generated by: Claude Opus (Anthropic, PBC)
//
// This code was AI-assisted and has been reviewed for accuracy and
// suitability for its intended purpose.
// -----------------------------------------------------------------------------

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicLong;

import static com.g20.CPEN431.A9.Constants.*;

/**
 * Push-Pull Gossip Protocol for group membership.
 *
 * Periodically:
 * 1. Increment own heartbeat counter
 * 2. Pick a random known node
 * 3. Send PUSH_PULL message (our full membership list)
 * 4. Receive their membership list in response
 * 5. Merge both lists (higher heartbeat wins)
 * 6. Mark nodes as failed if heartbeat hasn't updated in T_FAIL ms
 * 7. Remove nodes from list if failed for T_CLEANUP ms
 *
 * Thread-safe: the membership map is a ConcurrentHashMap and the
 * gossip thread is the only writer for most fields.
 */
public class GossipService {

    private final Node selfNode;
    private final DatagramSocket socket;
    private final ConsistentHashmap hashRing;

    // Membership table: nodeId -> NodeStatus
    private final ConcurrentHashMap<Integer, NodeStatus> membershipList = new ConcurrentHashMap<>();

    // Our own heartbeat counter
    private final AtomicLong heartbeatCounter = new AtomicLong(0);

    // Our generation (startup timestamp) — distinguishes incarnations across restarts.
    // Mutable: bumped on SIGSTOP/SIGCONT detection (time-jump) to force rejoin.
    private volatile long selfGeneration = System.currentTimeMillis();

    private volatile boolean running = true;
    private Thread gossipThread;

    // Optional callback invoked when a suspend/resume (time-jump) is detected
    private volatile Runnable onSuspendResumeDetected;

    // Warmup: ring is not stable until a few gossip cycles have run,
    // allowing membership to converge from multiple peers.
    private volatile boolean ringStable = false;

    public GossipService(Node selfNode, DatagramSocket socket, ConsistentHashmap hashRing) {
        this.selfNode = selfNode;
        this.socket = socket;
        this.hashRing = hashRing;

        // Add self to membership list and hash ring
        NodeStatus selfStatus = new NodeStatus(selfNode, 0, selfGeneration);
        selfStatus.setOnRing(true);
        membershipList.put(selfNode.id, selfStatus);
        hashRing.addNode(selfNode);
    }

    /**
     * Bootstrap: add known peers to the membership list so we can gossip with them.
     * Nodes are added to the membership list (alive) so gossip can reach them,
     * but NOT to the hash ring. Gossip responses will confirm which nodes are
     * actually alive and add them to the ring. This avoids routing to dead nodes
     * during a rejoin when some peers may be down.
     */
    public void addBootstrapNodes(List<Node> nodes) {
        for (Node node : nodes) {
            if (node.id == selfNode.id) continue;
            membershipList.putIfAbsent(node.id, new NodeStatus(node, 0, 0));
        }
    }

    /**
     * Start the gossip and failure detection background thread.
     */
    public void start() {
        gossipThread = new Thread(this::gossipAndFailureLoop, "Gossip-Thread");
        gossipThread.setDaemon(true);
        gossipThread.start();
    }

    /**
     * Whether the hash ring has stabilized after startup.
     * False during the brief warmup period (a few gossip cycles).
     */
    public boolean isRingStable() {
        return ringStable;
    }

    /**
     * Register a callback to be invoked when a suspend/resume (SIGSTOP/SIGCONT)
     * is detected via a wall-clock time jump.
     */
    public void setOnSuspendResumeDetected(Runnable callback) {
        this.onSuspendResumeDetected = callback;
    }

    /**
     * Stop the gossip service.
     */
    public void stop() {
        running = false;
        if (gossipThread != null) gossipThread.interrupt();
    }

    /**
     * Combined gossip and failure detection loop.
     * Gossip runs every GOSSIP_INTERVAL_MS. Failure detection runs when
     * GOSSIP_FAILURE_CHECK_INTERVAL_MS has elapsed since the last check.
     */
    private void gossipAndFailureLoop() {
        long lastFailureCheck = System.currentTimeMillis();
        long lastLoopTime = System.currentTimeMillis();
        int warmupCyclesElapsed = 0;
        int stableCount = 0;
        int lastRingSize = 0;

        while (running) {
            try {
                Thread.sleep(GOSSIP_INTERVAL_MS);
                if (!running) break;

                // --- Suspend/resume detection via wall-clock time jump ---
                // If we slept for GOSSIP_INTERVAL_MS but the wall clock advanced
                // by much more, we were likely suspended (SIGSTOP/SIGCONT).
                long now = System.currentTimeMillis();
                long elapsed = now - lastLoopTime;
                lastLoopTime = now;

                if (elapsed > GOSSIP_T_FAIL_MS) {
                    System.out.println("[Gossip] Time jump detected (" + elapsed
                            + "ms elapsed, expected ~" + GOSSIP_INTERVAL_MS
                            + "ms). Likely SIGSTOP/SIGCONT — bumping generation for rejoin.");
                    selfGeneration = System.currentTimeMillis();

                    // Reset warmup so ring can re-stabilize after rejoining
                    ringStable = false;
                    warmupCyclesElapsed = 0;
                    stableCount = 0;
                    lastRingSize = 0;

                    Runnable callback = onSuspendResumeDetected;
                    if (callback != null) {
                        callback.run();
                    }
                }

                // --- Warmup tracking: ring stable when size stops changing ---
                // Require at least one peer (size > 1) before declaring stable,
                // unless we've run long enough to conclude we're a single-node cluster.
                if (!ringStable) {
                    warmupCyclesElapsed++;
                    int currentRingSize = hashRing.size();
                    if (currentRingSize == lastRingSize) {
                        stableCount++;
                    } else {
                        stableCount = 0;
                        lastRingSize = currentRingSize;
                    }
                    boolean sizeStable = warmupCyclesElapsed >= GOSSIP_WARMUP_MIN_CYCLES
                            && stableCount >= GOSSIP_WARMUP_STABLE_CYCLES;
                    boolean hasPeers = currentRingSize > 1;
                    boolean likelySingleNode = warmupCyclesElapsed >= GOSSIP_WARMUP_MIN_CYCLES * 2;
                    if (sizeStable && (hasPeers || likelySingleNode)) {
                        ringStable = true;
                        System.out.println("[Gossip] Warmup complete — ring marked stable ("
                                + currentRingSize + " nodes)");
                    }
                }

                // --- Gossip work ---
                long hb = heartbeatCounter.incrementAndGet();

                // Keep self entry in membership list up-to-date
                NodeStatus selfStatus = membershipList.get(selfNode.id);
                if (selfStatus != null) {
                    selfStatus.updateSelfHeartbeat(hb);
                }

                List<NodeStatus> alivePeers = getAlivePeers();
                if (!alivePeers.isEmpty()) {
                    // Fanout: gossip to multiple random peers for faster convergence
                    int fanout = Math.min(GOSSIP_FANOUT, alivePeers.size());
                    java.util.Collections.shuffle(alivePeers);
                    for (int i = 0; i < fanout; i++) {
                        sendGossipMessage(alivePeers.get(i).getNode(), GossipMessage.TYPE_PUSH_PULL);
                    }

                    // Occasionally gossip with a random dead node (to detect rejoins)
                    if (ThreadLocalRandom.current().nextDouble() < 0.2) {
                        List<NodeStatus> deadPeers = getDeadPeers();
                        if (!deadPeers.isEmpty()) {
                            NodeStatus deadTarget = deadPeers.get(
                                    ThreadLocalRandom.current().nextInt(deadPeers.size()));
                            sendGossipMessage(deadTarget.getNode(), GossipMessage.TYPE_PUSH_PULL);
                        }
                    }
                }

                // --- Failure detection (on interval) ---
                now = System.currentTimeMillis();
                if (now - lastFailureCheck >= GOSSIP_FAILURE_CHECK_INTERVAL_MS) {
                    lastFailureCheck = now;

                    for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
                        int nodeId = entry.getKey();
                        NodeStatus status = entry.getValue();

                        if (nodeId == selfNode.id) continue;

                        if (status.markSuspectIfExpired(GOSSIP_T_FAIL_MS)) {
                            System.out.println("[Gossip] Node " + nodeId + " marked as SUSPECT");
                        } else if (status.confirmDeadIfSuspectExpired(GOSSIP_T_SUSPECT_MS, hashRing)) {
                            System.out.println("[Gossip] Node " + nodeId + " confirmed DEAD");
                        } else if (status.isCleanupReady(GOSSIP_T_CLEANUP_MS)) {
                            // Atomic removal: only remove if still DEAD (avoids race with
                            // concurrent rejoin in mergeEntries on the network thread)
                            NodeStatus newValue = membershipList.compute(nodeId, (k, v) ->
                                    (v != null && v.isDead()) ? null : v);
                            if (newValue == null) {
                                System.out.println("[Gossip] Node " + nodeId + " removed from membership list");
                            }
                        }
                    }
                }

            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                if (running) {
                    System.err.println("Gossip error: " + e.getMessage());
                }
            }
        }
    }

    /**
     * Handle an incoming gossip message from another node.
     */
    public void handleGossipMessage(GossipMessage msg, InetAddress senderAddress, int senderPort) {
        // Merge their membership list with ours
        mergeEntries(msg.getEntries());

        // If it's a push-pull or pull request, send our list back
        if (msg.getMessageType() == GossipMessage.TYPE_PUSH_PULL
                || msg.getMessageType() == GossipMessage.TYPE_PULL_REQUEST) {

            try {
                // Find the sender node to reply to
                NodeStatus senderStatus = membershipList.get(msg.getSenderId());
                if (senderStatus != null) {
                    sendGossipMessage(senderStatus.getNode(), GossipMessage.TYPE_PULL_RESPONSE);
                } else {
                    // We don't know this node yet, reply to the address we received from
                    sendGossipMessageTo(senderAddress, senderPort, GossipMessage.TYPE_PULL_RESPONSE);
                }
            } catch (Exception e) {
                System.err.println("Error sending gossip response: " + e.getMessage());
            }
        }
        // If it's a pull response or push, we already merged above, done.
    }

    /**
     * Merge incoming gossip entries with our membership list.
     */
    private void mergeEntries(List<GossipMessage.GossipEntry> entries) {
        for (GossipMessage.GossipEntry entry : entries) {
            if (entry.nodeId == selfNode.id) continue; // Don't update self from others

            NodeStatus existing = membershipList.get(entry.nodeId);
            if (existing == null) {
                // New node we haven't seen before
                if (entry.alive) {
                    Node newNode = new Node(entry.nodeId,
                            GossipMessage.intToIp(entry.ipAsInt), entry.port);
                    NodeStatus newStatus = new NodeStatus(newNode, entry.heartbeatCounter, entry.generation);
                    newStatus.setOnRing(true);
                    membershipList.put(entry.nodeId, newStatus);
                    hashRing.addNode(newNode);
                    System.out.println("[Gossip] Discovered new node " + entry.nodeId);
                }
            } else {
                if (entry.alive) {
                    // Existing node with alive report — update version and detect rejoin.
                    // Uses (generation, heartbeat) comparison to reject stale gossip.
                    boolean rejoined = existing.updateHeartbeatAndRejoinIfDead(
                            entry.generation, entry.heartbeatCounter, hashRing);
                    if (rejoined) {
                        System.out.println("[Gossip] Node " + entry.nodeId + " has REJOINED");
                    }
                } else {
                    // Existing node reported as dead by another peer — mark as SUSPECT.
                    // The node stays on the hash ring during suspicion; if it doesn't
                    // refute with a fresh heartbeat, it will be confirmed dead later.
                    if (existing.markSuspectFromGossip(entry.generation, entry.heartbeatCounter)) {
                        System.out.println("[Gossip] Node " + entry.nodeId + " marked SUSPECT via gossip");
                    }
                }
            }
        }
    }

    /**
     * Send our full membership list to a target node.
     */
    private void sendGossipMessage(Node target, byte messageType) {
        sendGossipMessageTo(target.ipaddress, target.port, messageType);
    }

    private void sendGossipMessageTo(InetAddress address, int port, byte messageType) {
        try {
            GossipMessage msg = buildGossipMessage(messageType);
            byte[] data = msg.serialize();
            DatagramPacket packet = new DatagramPacket(data, data.length, address, port);
            socket.send(packet);
        } catch (IOException e) {
            // Silently ignore send failures (node may be down)
        }
    }

    /**
     * Build a gossip message with our current membership list.
     */
    private GossipMessage buildGossipMessage(byte messageType) {
        GossipMessage msg = new GossipMessage(messageType, selfNode.id);

        // Always include self with current heartbeat and generation
        msg.addEntry(selfNode.id,
                GossipMessage.ipToInt(selfNode.ipaddress),
                selfNode.port,
                heartbeatCounter.get(),
                selfGeneration,
                true);

        // Collect peer entries, shuffle and cap to avoid exceeding UDP MTU
        List<Map.Entry<Integer, NodeStatus>> peers = new ArrayList<>();
        for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
            if (entry.getKey() == selfNode.id) continue;
            peers.add(entry);
        }
        java.util.Collections.shuffle(peers);
        int limit = Math.min(peers.size(), GOSSIP_MAX_ENTRIES - 1); // -1 for self entry
        for (int i = 0; i < limit; i++) {
            Map.Entry<Integer, NodeStatus> entry = peers.get(i);
            NodeStatus status = entry.getValue();
    long[] snapshot = status.getSnapshot(); // [heartbeat, alive, generation]
            msg.addEntry(
                    entry.getKey(),
                    GossipMessage.ipToInt(status.getNode().ipaddress),
                    status.getNode().port,
                    snapshot[0],
                    snapshot[2],  // generation
                    snapshot[1] == 1
            );
        }

        return msg;
    }

    /**
     * Get the number of members on the ring (ALIVE or SUSPECT, including self).
     */
    public int getAliveMemberCount() {
        int count = 0;
        for (NodeStatus status : membershipList.values()) {
            if (status.isOnRing()) count++;
        }
        return count;
    }

    /**
     * Get the consistent hash ring.
     */
    public ConsistentHashmap getHashRing() {
        return hashRing;
    }

    /**
     * Get self node.
     */
    public Node getSelfNode() {
        return selfNode;
    }

    /**
     * Get list of non-dead peers (ALIVE or SUSPECT), excluding self.
     * Includes bootstrap nodes not yet on the ring, so gossip can confirm them.
     * SUSPECT peers are included so we can potentially receive a fresh heartbeat.
     */
    private List<NodeStatus> getAlivePeers() {
        List<NodeStatus> peers = new ArrayList<>();
        for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
            if (entry.getKey() != selfNode.id && !entry.getValue().isDead()) {
                peers.add(entry.getValue());
            }
        }
        return peers;
    }

    /**
     * Get list of confirmed-dead peers.
     */
    private List<NodeStatus> getDeadPeers() {
        List<NodeStatus> dead = new ArrayList<>();
        for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
            if (entry.getKey() != selfNode.id && entry.getValue().isDead()) {
                dead.add(entry.getValue());
            }
        }
        return dead;
    }
}