package com.g20.CPEN431.A9.network;

import com.g20.CPEN431.A9.storage.ConsistentHashmap;

// -----------------------------------------------------------------------------
// AI-GENERATED CODE ACKNOWLEDGEMENT
// -----------------------------------------------------------------------------
// Code generated by: Claude Opus (Anthropic, PBC)
//
// This code was AI-assisted and has been reviewed for accuracy and
// suitability for its intended purpose.
// -----------------------------------------------------------------------------

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicLong;

import static com.g20.CPEN431.A9.Constants.*;

/**
 * Push-Pull Gossip Protocol for group membership.
 *
 * Periodically:
 * 1. Increment own heartbeat counter
 * 2. Pick a random known node
 * 3. Send PUSH_PULL message (our full membership list)
 * 4. Receive their membership list in response
 * 5. Merge both lists (higher heartbeat wins)
 * 6. Mark nodes as failed if heartbeat hasn't updated in T_FAIL ms
 * 7. Remove nodes from list if failed for T_CLEANUP ms
 *
 * Thread-safe: the membership map is a ConcurrentHashMap and the
 * gossip thread is the only writer for most fields.
 */
public class GossipService {

    private final Node selfNode;
    private final DatagramSocket socket;
    private final ConsistentHashmap hashRing;

    // Membership table: nodeId -> NodeStatus
    private final ConcurrentHashMap<Integer, NodeStatus> membershipList = new ConcurrentHashMap<>();

    // Our own heartbeat counter
    private final AtomicLong heartbeatCounter = new AtomicLong(0);

    private volatile boolean running = true;
    private Thread gossipThread;
    private Thread failureDetectorThread;

    public GossipService(Node selfNode, DatagramSocket socket, ConsistentHashmap hashRing) {
        this.selfNode = selfNode;
        this.socket = socket;
        this.hashRing = hashRing;

        // Add self to membership list and hash ring
        membershipList.put(selfNode.id, new NodeStatus(selfNode, 0));
        hashRing.addNode(selfNode);
    }

    /**
     * Bootstrap: add known peers to the membership list so we can gossip with them.
     * They are marked alive initially; if they don't respond, failure detection will handle it.
     */
    public void addBootstrapNodes(List<Node> nodes) {
        for (Node node : nodes) {
            if (node.id == selfNode.id) continue;
            membershipList.putIfAbsent(node.id, new NodeStatus(node, 0));
            hashRing.addNode(node);
        }
    }

    /**
     * Start the gossip and failure detection background threads.
     */
    public void start() {
        gossipThread = new Thread(this::gossipLoop, "Gossip-Thread");
        gossipThread.setDaemon(true);
        gossipThread.start();

        failureDetectorThread = new Thread(this::failureDetectionLoop, "FailureDetector-Thread");
        failureDetectorThread.setDaemon(true);
        failureDetectorThread.start();
    }

    /**
     * Stop the gossip service.
     */
    public void stop() {
        running = false;
        if (gossipThread != null) gossipThread.interrupt();
        if (failureDetectorThread != null) failureDetectorThread.interrupt();
    }

    /**
     * Main gossip loop: periodically sends push-pull messages to random peers.
     */
    private void gossipLoop() {
        while (running) {
            try {
                Thread.sleep(GOSSIP_INTERVAL_MS);
                if (!running) break;

                // Increment our own heartbeat
                heartbeatCounter.incrementAndGet();

                // Pick a random alive peer to gossip with
                List<NodeStatus> alivePeers = getAlivePeers();
                if (alivePeers.isEmpty()) continue;

                NodeStatus target = alivePeers.get(
                        ThreadLocalRandom.current().nextInt(alivePeers.size()));

                // Send push-pull message
                sendGossipMessage(target.getNode(), GossipMessage.TYPE_PUSH_PULL);

                // Occasionally gossip with a random dead node (to detect rejoins)
                if (ThreadLocalRandom.current().nextDouble() < 0.2) {
                    List<NodeStatus> deadPeers = getDeadPeers();
                    if (!deadPeers.isEmpty()) {
                        NodeStatus deadTarget = deadPeers.get(
                                ThreadLocalRandom.current().nextInt(deadPeers.size()));
                        sendGossipMessage(deadTarget.getNode(), GossipMessage.TYPE_PUSH_PULL);
                    }
                }

            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                if (running) {
                    System.err.println("Gossip error: " + e.getMessage());
                }
            }
        }
    }

    /**
     * Failure detection loop: periodically checks for nodes that haven't
     * had their heartbeat updated recently.
     */
    private void failureDetectionLoop() {
        while (running) {
            try {
                Thread.sleep(GOSSIP_FAILURE_CHECK_INTERVAL_MS);
                if (!running) break;

                Iterator<Map.Entry<Integer, NodeStatus>> it = membershipList.entrySet().iterator();

                while (it.hasNext()) {
                    Map.Entry<Integer, NodeStatus> entry = it.next();
                    int nodeId = entry.getKey();
                    NodeStatus status = entry.getValue();

                    // Don't check self
                    if (nodeId == selfNode.id) continue;

                    if (status.markFailedIfExpired(GOSSIP_T_FAIL_MS, hashRing)) {
                        System.out.println("[Gossip] Node " + nodeId + " marked as FAILED");
                    } else if (status.isCleanupReady(GOSSIP_T_CLEANUP_MS)) {
                        // Remove from membership list entirely
                        it.remove();
                        System.out.println("[Gossip] Node " + nodeId + " removed from membership list");
                    }
                }

            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                if (running) {
                    System.err.println("Failure detection error: " + e.getMessage());
                }
            }
        }
    }

    /**
     * Handle an incoming gossip message from another node.
     */
    public void handleGossipMessage(GossipMessage msg, InetAddress senderAddress, int senderPort) {
        // Merge their membership list with ours
        mergeEntries(msg.getEntries());

        // If it's a push-pull or pull request, send our list back
        if (msg.getMessageType() == GossipMessage.TYPE_PUSH_PULL
                || msg.getMessageType() == GossipMessage.TYPE_PULL_REQUEST) {

            try {
                // Find the sender node to reply to
                NodeStatus senderStatus = membershipList.get(msg.getSenderId());
                if (senderStatus != null) {
                    sendGossipMessage(senderStatus.getNode(), GossipMessage.TYPE_PULL_RESPONSE);
                } else {
                    // We don't know this node yet, reply to the address we received from
                    sendGossipMessageTo(senderAddress, senderPort, GossipMessage.TYPE_PULL_RESPONSE);
                }
            } catch (Exception e) {
                System.err.println("Error sending gossip response: " + e.getMessage());
            }
        }
        // If it's a pull response or push, we already merged above, done.
    }

    /**
     * Merge incoming gossip entries with our membership list.
     */
    private void mergeEntries(List<GossipMessage.GossipEntry> entries) {
        for (GossipMessage.GossipEntry entry : entries) {
            if (entry.nodeId == selfNode.id) continue; // Don't update self from others

            NodeStatus existing = membershipList.get(entry.nodeId);
            if (existing == null) {
                // New node we haven't seen before
                if (entry.alive) {
                    Node newNode = new Node(entry.nodeId,
                            GossipMessage.intToIp(entry.ipAsInt), entry.port);
                    NodeStatus newStatus = new NodeStatus(newNode, entry.heartbeatCounter);
                    membershipList.put(entry.nodeId, newStatus);
                    hashRing.addNode(newNode);
                    System.out.println("[Gossip] Discovered new node " + entry.nodeId);
                }
            } else {
                // Existing node - atomically update heartbeat and detect rejoin
                boolean rejoined = existing.updateHeartbeatAndRejoinIfDead(entry.heartbeatCounter, hashRing);
                if (rejoined) {
                    System.out.println("[Gossip] Node " + entry.nodeId + " has REJOINED");
                }
            }
        }
    }

    /**
     * Send our full membership list to a target node.
     */
    private void sendGossipMessage(Node target, byte messageType) {
        sendGossipMessageTo(target.ipaddress, target.port, messageType);
    }

    private void sendGossipMessageTo(InetAddress address, int port, byte messageType) {
        try {
            GossipMessage msg = buildGossipMessage(messageType);
            byte[] data = msg.serialize();
            DatagramPacket packet = new DatagramPacket(data, data.length, address, port);
            socket.send(packet);
        } catch (IOException e) {
            // Silently ignore send failures (node may be down)
        }
    }

    /**
     * Build a gossip message with our current membership list.
     */
    private GossipMessage buildGossipMessage(byte messageType) {
        GossipMessage msg = new GossipMessage(messageType, selfNode.id);

        // Add self with current heartbeat
        msg.addEntry(selfNode.id,
                GossipMessage.ipToInt(selfNode.ipaddress),
                selfNode.port,
                heartbeatCounter.get(),
                true);

        // Add all known nodes
        for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
            if (entry.getKey() == selfNode.id) continue;
            NodeStatus status = entry.getValue();
            msg.addEntry(
                    entry.getKey(),
                    GossipMessage.ipToInt(status.getNode().ipaddress),
                    status.getNode().port,
                    status.getHeartbeatCounter(),
                    status.isAlive()
            );
        }

        return msg;
    }

    /**
     * Get the number of alive members (including self).
     */
    public int getAliveMemberCount() {
        int count = 0;
        for (NodeStatus status : membershipList.values()) {
            if (status.isAlive()) count++;
        }
        return count;
    }

    /**
     * Get the consistent hash ring.
     */
    public ConsistentHashmap getHashRing() {
        return hashRing;
    }

    /**
     * Get self node.
     */
    public Node getSelfNode() {
        return selfNode;
    }

    /**
     * Get list of alive peers (excluding self).
     */
    private List<NodeStatus> getAlivePeers() {
        List<NodeStatus> peers = new ArrayList<>();
        for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
            if (entry.getKey() != selfNode.id && entry.getValue().isAlive()) {
                peers.add(entry.getValue());
            }
        }
        return peers;
    }

    /**
     * Get list of dead peers.
     */
    private List<NodeStatus> getDeadPeers() {
        List<NodeStatus> dead = new ArrayList<>();
        for (Map.Entry<Integer, NodeStatus> entry : membershipList.entrySet()) {
            if (entry.getKey() != selfNode.id && !entry.getValue().isAlive()) {
                dead.add(entry.getValue());
            }
        }
        return dead;
    }
}