package com.g20.CPEN431.A9.network;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;

import java.net.DatagramPacket;
import java.net.InetAddress;

// This code was in part generated by an LLM.
public class ReceivedPacket {
    public final Msg msg;
    public final InetAddress address;
    public final int port;
    public final boolean isForwarded;

    // For forwarded requests: the original client to relay the response to
    public final InetAddress originalClientAddress;
    public final int originalClientPort;

    // Multi-hop forwarding state
    public final int hopCount;
    public final int senderNodeId;     // Node ID of the last forwarder (for loop-breaking)
    public final byte[] hopChainBytes; // Raw hop chain [IP(4)+port(4)] * hopCount, for response routing

    private static final byte[] EMPTY_CHAIN = new byte[0];

    public ReceivedPacket(Msg msg, DatagramPacket packet, boolean isForwarded) {
        this(msg, packet, isForwarded, null, 0, 0, 0, EMPTY_CHAIN);
    }

    public ReceivedPacket(Msg msg, DatagramPacket packet, boolean isForwarded,
                          InetAddress originalClientAddress, int originalClientPort,
                          int hopCount, int senderNodeId, byte[] hopChainBytes) {
        this.msg = msg;
        this.address = packet.getAddress();
        this.port = packet.getPort();
        this.isForwarded = isForwarded;
        this.originalClientAddress = originalClientAddress;
        this.originalClientPort = originalClientPort;
        this.hopCount = hopCount;
        this.senderNodeId = senderNodeId;
        this.hopChainBytes = hopChainBytes;
    }
}
