package com.g20.CPEN431.A9.network;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;

import java.net.DatagramPacket;
import java.net.InetAddress;

// This code was in part generated by an LLM.
public class ReceivedPacket {
    public final Msg msg;
    public final InetAddress address;
    public final int port;
    public final boolean isForwarded;

    // For forwarded requests: the original client to relay the response to
    public final InetAddress originalClientAddress;
    public final int originalClientPort;

    // Number of forwarding hops this request has taken
    public final int hopCount;

    public ReceivedPacket(Msg msg, DatagramPacket packet, boolean isForwarded) {
        this(msg, packet, isForwarded, null, 0, 0);
    }

    public ReceivedPacket(Msg msg, DatagramPacket packet, boolean isForwarded,
                          InetAddress originalClientAddress, int originalClientPort,
                          int hopCount) {
        this.msg = msg;
        this.address = packet.getAddress();
        this.port = packet.getPort();
        this.isForwarded = isForwarded;
        this.originalClientAddress = originalClientAddress;
        this.originalClientPort = originalClientPort;
        this.hopCount = hopCount;
    }
}
