package com.g20.CPEN431.A9.server;

import com.g20.CPEN431.A9.network.GossipService;
import com.g20.CPEN431.A9.storage.KeyValueStore;
import com.g20.CPEN431.A9.Main;

import ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest;
import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import com.google.protobuf.ByteString;

import static com.g20.CPEN431.A9.Constants.*;
import static com.g20.CPEN431.A9.util.MessageUtils.*;

// This code was in part generated by an LLM.
public final class RequestHandler {

    private RequestHandler() {}

    /**
     * Process a request, with access to gossip service for membership info.
     */
    public static KVResponse processRequest(KVRequest request, GossipService gossipService) {
        int command = request.getCommand();

        switch (command) {
            case CMD_PUT:
                return handlePut(request);
            case CMD_GET:
                return handleGet(request);
            case CMD_REMOVE:
                return handleRemove(request);
            case CMD_SHUTDOWN:
                return handleShutdown();
            case CMD_WIPEOUT:
                return handleWipeout();
            case CMD_IS_ALIVE:
                return handleIsAlive();
            case CMD_GET_PID:
                return handleGetPid();
            case CMD_GET_MEMBERSHIP_COUNT:
                return handleGetMembershipCount(gossipService);
            default:
                return buildKVResponse(ERR_UNKNOWN_COMMAND);
        }
    }

    private static KVResponse handlePut(KVRequest request) {
        if (!request.hasKey() || request.getKey().isEmpty()) {
            return buildKVResponse(ERR_INVALID_KEY);
        }
        if (request.getKey().size() > MAX_KEY_LENGTH) {
            return buildKVResponse(ERR_INVALID_KEY);
        }
        if (!request.hasValue()) {
            return buildKVResponse(ERR_INVALID_VALUE);
        }
        if (request.getValue().size() > MAX_VALUE_LENGTH) {
            return buildKVResponse(ERR_INVALID_VALUE);
        }

        ByteString key = request.getKey();
        ByteString value = request.getValue();
        int version = request.hasVersion() ? request.getVersion() : 0;

        if (!KeyValueStore.canAddEntry(key.size(), value.size())) {
            return buildOutOfSpaceResponse();
        }

        KeyValueStore.put(key, value, version);
        return buildKVResponse(ERR_SUCCESS);
    }

    private static KVResponse handleGet(KVRequest request) {
        if (!request.hasKey() || request.getKey().isEmpty()) {
            return buildKVResponse(ERR_INVALID_KEY);
        }
        if (request.getKey().size() > MAX_KEY_LENGTH) {
            return buildKVResponse(ERR_INVALID_KEY);
        }

        ByteString key = request.getKey();
        KeyValueStore.StoragePayload payload = KeyValueStore.get(key);

        if (payload == null) {
            return buildKVResponse(ERR_NON_EXISTENT_KEY);
        }

        return buildKVResponse(ERR_SUCCESS, payload.getValue(), payload.getVersion());
    }

    private static KVResponse handleRemove(KVRequest request) {
        if (!request.hasKey() || request.getKey().isEmpty()) {
            return buildKVResponse(ERR_INVALID_KEY);
        }
        if (request.getKey().size() > MAX_KEY_LENGTH) {
            return buildKVResponse(ERR_INVALID_KEY);
        }

        ByteString key = request.getKey();
        KeyValueStore.StoragePayload removed = KeyValueStore.remove(key);

        if (removed == null) {
            return buildKVResponse(ERR_NON_EXISTENT_KEY);
        }

        return buildKVResponse(ERR_SUCCESS);
    }

    private static KVResponse handleShutdown() {
        // Must exit immediately per spec - no cleanup, no gossip, just crash
        System.exit(0);
        return buildKVResponse(ERR_SUCCESS); // unreachable
    }

    private static KVResponse handleWipeout() {
        KeyValueStore.clear();
        return buildKVResponse(ERR_SUCCESS);
    }

    private static KVResponse handleIsAlive() {
        return buildKVResponse(ERR_SUCCESS);
    }

    private static KVResponse handleGetPid() {
        // Use pre-computed PID from Main to avoid slow ProcessHandle calls under NetEm
        return KVResponse.newBuilder()
                .setErrCode(ERR_SUCCESS)
                .setPid(Main.PID)
                .build();
    }

    private static KVResponse handleGetMembershipCount(GossipService gossipService) {
        int count = gossipService != null ? gossipService.getAliveMemberCount() : 1;
        return KVResponse.newBuilder()
                .setErrCode(ERR_SUCCESS)
                .setMembershipCount(count)
                .build();
    }
}