package com.g20.CPEN431.A9.server;

import com.g20.CPEN431.A9.network.GossipService;
import com.g20.CPEN431.A9.network.KeyTransferService;
import com.g20.CPEN431.A9.network.ReceivedPacket;
import com.g20.CPEN431.A9.storage.ConsistentHashmap;
import com.g20.CPEN431.A9.network.GossipMessage;
import com.g20.CPEN431.A9.network.Node;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.List;

import static com.g20.CPEN431.A9.Constants.*;
import static com.g20.CPEN431.A9.util.MessageUtils.*;

// This code was in part generated by an LLM.
public class Server {
    private final DatagramSocket socket;
    private final Worker[] workers;
    private volatile boolean running = true;

    private final GossipService gossipService;
    private final KeyTransferService keyTransferService;
    private final Node selfNode;

    public Server(int port, List<Node> allNodes) throws SocketException {
        this.socket = new DatagramSocket(port);

        try {
            socket.setReceiveBufferSize(4 * 1024 * 1024);
        } catch (SocketException e) {
            // Best effort
        }

        this.selfNode = findSelf(allNodes, port);
        if (selfNode == null) {
            throw new RuntimeException(
                    "Could not find self in nodes list for port " + port
                            + ". Make sure the nodes file contains this node's address.");
        }
        System.out.println("Self node: id=" + selfNode.id
                + " addr=" + selfNode.ipaddress.getHostAddress() + ":" + selfNode.port);

        ConsistentHashmap hashRing = new ConsistentHashmap(VIRTUAL_NODES);
        this.gossipService = new GossipService(selfNode, socket, hashRing);
        gossipService.addBootstrapNodes(allNodes);

        this.keyTransferService = new KeyTransferService(selfNode, socket, hashRing);
        gossipService.setKeyTransferService(keyTransferService);

        this.workers = new Worker[NUM_WORKERS];
        for (int i = 0; i < NUM_WORKERS; i++) {
            workers[i] = new Worker(i, this.socket, gossipService, keyTransferService, selfNode);
        }
    }

    private Node findSelf(List<Node> allNodes, int port) {
        try {
            InetAddress localAddr = InetAddress.getLocalHost();
            String localHostname = localAddr.getHostName();
            String localIp = localAddr.getHostAddress();

            for (Node node : allNodes) {
                if (node.port != port) continue;
                String nodeIp = node.ipaddress.getHostAddress();
                String nodeHostname = node.ipaddress.getHostName();
                if (nodeIp.equals(localIp)
                        || nodeHostname.equals(localHostname)
                        || node.ipaddress.isLoopbackAddress()
                        || nodeIp.equals("127.0.0.1")
                        || nodeIp.equals("0.0.0.0")) {
                    return node;
                }
            }
            for (Node node : allNodes) {
                if (node.port == port) return node;
            }
        } catch (Exception e) {
            System.err.println("Error finding self node: " + e.getMessage());
        }
        return null;
    }

    public void start() {
        gossipService.start();
        keyTransferService.start();

        for (Worker worker : workers) {
            worker.start();
        }

        byte[] buffer = new byte[MAX_PACKET_SIZE];
        DatagramPacket packet = new DatagramPacket(buffer, buffer.length);

        while (running) {
            try {
                socket.receive(packet);
                int len = packet.getLength();

                if (GossipMessage.isGossipMessage(buffer, len)) {
                    handleGossipPacket(buffer, packet);
                    continue;
                }

                if (KeyTransferService.isKeyTransferMessage(buffer, len)) {
                    byte[] copy = new byte[len];
                    System.arraycopy(buffer, 0, copy, 0, len);
                    keyTransferService.handleKeyTransferPacket(copy, len);
                    continue;
                }

                if (KeyTransferService.isTransferCompleteMessage(buffer, len)) {
                    byte[] copy = new byte[len];
                    System.arraycopy(buffer, 0, copy, 0, len);
                    keyTransferService.handleTransferComplete(copy, len);
                    continue;
                }

                if (isResponseMessage(buffer, len)) {
                    relayForwardResponse(buffer, len);
                    continue;
                }

                // Check if this is a forwarded request
                boolean isForwarded = isForwardedMessage(buffer, len);

                InetAddress originalClientAddress = null;
                int originalClientPort = 0;
                int hopCount = 0;
                int senderNodeId = 0;
                byte[] hopChainBytes = new byte[0];
                int msgOffset = 0;

                if (isForwarded) {
                    // Parse forward header:
                    // FORWARD_MAGIC(4) + clientIP(4) + clientPort(4) + hopCount(1) + senderNodeId(4) + hopChain
                    originalClientAddress = InetAddress.getByAddress(new byte[]{
                            buffer[4], buffer[5], buffer[6], buffer[7]
                    });
                    originalClientPort = ((buffer[8] & 0xFF) << 24)
                            | ((buffer[9] & 0xFF) << 16)
                            | ((buffer[10] & 0xFF) << 8)
                            | (buffer[11] & 0xFF);
                    hopCount = buffer[12] & 0xFF;
                    senderNodeId = ((buffer[13] & 0xFF) << 24)
                            | ((buffer[14] & 0xFF) << 16)
                            | ((buffer[15] & 0xFF) << 8)
                            | (buffer[16] & 0xFF);

                    int chainSize = hopCount * HOP_ENTRY_SIZE;
                    hopChainBytes = new byte[chainSize];
                    System.arraycopy(buffer, FORWARD_HEADER_BASE_SIZE, hopChainBytes, 0, chainSize);

                    msgOffset = FORWARD_HEADER_BASE_SIZE + chainSize;
                }

                Msg msg;
                try {
                    msg = Msg.parseFrom(ByteString.copyFrom(buffer, msgOffset, len - msgOffset));
                } catch (InvalidProtocolBufferException e) {
                    continue;
                }

                ReceivedPacket received = new ReceivedPacket(
                        msg, packet, isForwarded, originalClientAddress, originalClientPort,
                        hopCount, senderNodeId, hopChainBytes);

                int workerIndex = Math.abs(msg.getMessageID().hashCode() % NUM_WORKERS);
                Worker worker = workers[workerIndex];

                if (!worker.offer(received)) {
                    if (!verifyChecksum(msg)) continue;
                    handleOverload(received, msg.getMessageID());
                }

            } catch (IOException e) {
                if (running) e.printStackTrace();
            }
        }
    }

    /**
     * Relay a forward response through the hop chain back to the client.
     *
     * Response header: RESPONSE_MAGIC(4) + clientIP(4) + clientPort(4) + chainLen(1) + relay_chain + payload
     *
     * If chainLen == 0: relay directly to clientIP:clientPort.
     * If chainLen > 0: pop the last relay entry, send to that address with chainLen-1.
     */
    private void relayForwardResponse(byte[] buffer, int length) {
        try {
            InetAddress clientAddress = InetAddress.getByAddress(new byte[]{
                    buffer[4], buffer[5], buffer[6], buffer[7]
            });
            int clientPort = ((buffer[8] & 0xFF) << 24)
                    | ((buffer[9] & 0xFF) << 16)
                    | ((buffer[10] & 0xFF) << 8)
                    | (buffer[11] & 0xFF);
            int chainLen = buffer[12] & 0xFF;
            int fullHeaderSize = responseHeaderSize(chainLen);

            if (chainLen == 0) {
                // Final hop: send directly to client
                DatagramPacket responsePacket = new DatagramPacket(
                        buffer, fullHeaderSize, length - fullHeaderSize,
                        clientAddress, clientPort);
                socket.send(responsePacket);
            } else {
                // Pop the last relay entry as the next hop
                int lastEntryOffset = RESPONSE_HEADER_BASE_SIZE + (chainLen - 1) * HOP_ENTRY_SIZE;
                InetAddress nextHop = InetAddress.getByAddress(new byte[]{
                        buffer[lastEntryOffset], buffer[lastEntryOffset + 1],
                        buffer[lastEntryOffset + 2], buffer[lastEntryOffset + 3]
                });
                int nextPort = ((buffer[lastEntryOffset + 4] & 0xFF) << 24)
                        | ((buffer[lastEntryOffset + 5] & 0xFF) << 16)
                        | ((buffer[lastEntryOffset + 6] & 0xFF) << 8)
                        | (buffer[lastEntryOffset + 7] & 0xFF);

                // Build new response with chainLen-1
                int newChainLen = chainLen - 1;
                int newHeaderSize = responseHeaderSize(newChainLen);
                int payloadLen = length - fullHeaderSize;
                byte[] newBuf = new byte[newHeaderSize + payloadLen];

                // Copy magic + clientIP + clientPort (12 bytes)
                System.arraycopy(buffer, 0, newBuf, 0, 12);
                newBuf[12] = (byte) newChainLen;
                // Copy remaining relay entries (all except the last one we just popped)
                if (newChainLen > 0) {
                    System.arraycopy(buffer, RESPONSE_HEADER_BASE_SIZE,
                            newBuf, RESPONSE_HEADER_BASE_SIZE, newChainLen * HOP_ENTRY_SIZE);
                }
                // Copy payload
                System.arraycopy(buffer, fullHeaderSize, newBuf, newHeaderSize, payloadLen);

                socket.send(new DatagramPacket(newBuf, newBuf.length, nextHop, nextPort));
            }
        } catch (IOException e) {
            // Best effort
        }
    }

    private void handleGossipPacket(byte[] buffer, DatagramPacket packet) {
        try {
            GossipMessage msg = GossipMessage.deserialize(buffer, packet.getLength());
            if (msg != null) {
                gossipService.handleGossipMessage(msg, packet.getAddress(), packet.getPort());
            }
        } catch (Exception e) {
            System.err.println("Error handling gossip packet: " + e.getMessage());
        }
    }

    /**
     * Handle overload when worker queue is full.
     * Builds response with correct relay chain for multi-hop forwarded requests.
     */
    private void handleOverload(ReceivedPacket packet, ByteString messageId) {
        try {
            byte[] response = buildMsg(messageId, buildOverloadResponse(301));

            if (packet.isForwarded && packet.originalClientAddress != null) {
                // Build response header with relay chain
                int chainLen = Math.max(0, packet.hopCount - 1);
                int headerSize = responseHeaderSize(chainLen);
                byte[] prefixed = new byte[headerSize + response.length];

                System.arraycopy(RESPONSE_MAGIC, 0, prefixed, 0, 4);
                byte[] clientIp = packet.originalClientAddress.getAddress();
                System.arraycopy(clientIp, 0, prefixed, 4, 4);
                int clientPort = packet.originalClientPort;
                prefixed[8] = (byte) (clientPort >> 24);
                prefixed[9] = (byte) (clientPort >> 16);
                prefixed[10] = (byte) (clientPort >> 8);
                prefixed[11] = (byte) clientPort;
                prefixed[12] = (byte) chainLen;
                // Copy relay chain (all hop entries except the last one)
                if (chainLen > 0) {
                    System.arraycopy(packet.hopChainBytes, 0, prefixed, RESPONSE_HEADER_BASE_SIZE,
                            chainLen * HOP_ENTRY_SIZE);
                }
                System.arraycopy(response, 0, prefixed, headerSize, response.length);

                socket.send(new DatagramPacket(prefixed, prefixed.length,
                        packet.address, packet.port));
            } else {
                socket.send(new DatagramPacket(response, response.length,
                        packet.address, packet.port));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private static boolean isForwardedMessage(byte[] data, int length) {
        if (length < FORWARD_HEADER_BASE_SIZE) return false;
        return data[0] == FORWARD_MAGIC[0]
                && data[1] == FORWARD_MAGIC[1]
                && data[2] == FORWARD_MAGIC[2]
                && data[3] == FORWARD_MAGIC[3];
    }

    private static boolean isResponseMessage(byte[] data, int length) {
        if (length < RESPONSE_HEADER_BASE_SIZE) return false;
        return data[0] == RESPONSE_MAGIC[0]
                && data[1] == RESPONSE_MAGIC[1]
                && data[2] == RESPONSE_MAGIC[2]
                && data[3] == RESPONSE_MAGIC[3];
    }

    public void stop() {
        running = false;
        gossipService.stop();
        keyTransferService.stop();
        for (Worker worker : workers) {
            worker.shutdown();
        }
        socket.close();
    }
}
