package com.g20.CPEN431.A9.server;

import com.g20.CPEN431.A9.network.GossipService;
import com.g20.CPEN431.A9.network.KeyTransferService;
import com.g20.CPEN431.A9.network.ReceivedPacket;
import com.g20.CPEN431.A9.storage.ConsistentHashmap;
import com.g20.CPEN431.A9.network.GossipMessage;
import com.g20.CPEN431.A9.network.Node;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.List;

import static com.g20.CPEN431.A9.Constants.*;
import static com.g20.CPEN431.A9.util.MessageUtils.*;

// This code was in part generated by an LLM.
public class Server {
    private final DatagramSocket socket;
    private final Worker[] workers;
    private volatile boolean running = true;

    private final GossipService gossipService;
    private final KeyTransferService keyTransferService;
    private final Node selfNode;

    public Server(int port, List<Node> allNodes) throws SocketException {
        this.socket = new DatagramSocket(port);

        // Increase socket receive buffer to reduce packet drops under load
        try {
            socket.setReceiveBufferSize(4 * 1024 * 1024); // 4MB
        } catch (SocketException e) {
            // Best effort — OS may cap this
        }

        // Identify self from the node list
        this.selfNode = findSelf(allNodes, port);
        if (selfNode == null) {
            throw new RuntimeException(
                    "Could not find self in nodes list for port " + port
                            + ". Make sure the nodes file contains this node's address.");
        }
        System.out.println("Self node: id=" + selfNode.id
                + " addr=" + selfNode.ipaddress.getHostAddress() + ":" + selfNode.port);

        // Initialize consistent hash ring and gossip service
        ConsistentHashmap hashRing = new ConsistentHashmap(VIRTUAL_NODES);
        this.gossipService = new GossipService(selfNode, socket, hashRing);
        gossipService.addBootstrapNodes(allNodes);

        // Initialize key transfer service and wire to gossip
        this.keyTransferService = new KeyTransferService(selfNode, socket, hashRing);
        gossipService.setKeyTransferService(keyTransferService);

        // Create workers
        this.workers = new Worker[NUM_WORKERS];
        for (int i = 0; i < NUM_WORKERS; i++) {
            workers[i] = new Worker(i, this.socket, gossipService, keyTransferService);
        }
    }

    /**
     * Find our own Node object from the list by matching port and local addresses.
     */
    private Node findSelf(List<Node> allNodes, int port) {
        try {
            InetAddress localAddr = InetAddress.getLocalHost();
            String localHostname = localAddr.getHostName();
            String localIp = localAddr.getHostAddress();

            for (Node node : allNodes) {
                if (node.port != port) continue;

                String nodeIp = node.ipaddress.getHostAddress();
                String nodeHostname = node.ipaddress.getHostName();

                // Match by IP, hostname, or loopback
                if (nodeIp.equals(localIp)
                        || nodeHostname.equals(localHostname)
                        || node.ipaddress.isLoopbackAddress()
                        || nodeIp.equals("127.0.0.1")
                        || nodeIp.equals("0.0.0.0")) {
                    return node;
                }
            }

            // Fallback: if running locally with multiple processes, match by port only
            // and pick the first node with this port
            for (Node node : allNodes) {
                if (node.port == port) {
                    return node;
                }
            }
        } catch (Exception e) {
            System.err.println("Error finding self node: " + e.getMessage());
        }
        return null;
    }

    public void start() {
        // Start gossip service
        gossipService.start();

        // Start key transfer service
        keyTransferService.start();

        // Start worker threads
        for (Worker worker : workers) {
            worker.start();
        }

        byte[] buffer = new byte[MAX_PACKET_SIZE];
        DatagramPacket packet = new DatagramPacket(buffer, buffer.length);

        while (running) {
            try {
                socket.receive(packet);
                int len = packet.getLength();

                // Check if this is a gossip message (internal protocol)
                if (GossipMessage.isGossipMessage(buffer, len)) {
                    handleGossipPacket(buffer, packet);
                    continue;
                }

                // Check if this is a key transfer data packet
                if (KeyTransferService.isKeyTransferMessage(buffer, len)) {
                    byte[] copy = new byte[len];
                    System.arraycopy(buffer, 0, copy, 0, len);
                    keyTransferService.handleKeyTransferPacket(copy, len);
                    continue;
                }

                // Check if this is a transfer complete notification
                if (KeyTransferService.isTransferCompleteMessage(buffer, len)) {
                    byte[] copy = new byte[len];
                    System.arraycopy(buffer, 0, copy, 0, len);
                    keyTransferService.handleTransferComplete(copy, len);
                    continue;
                }

                // Check if this is a response to a forwarded request (from target node)
                if (isResponseMessage(buffer, len)) {
                    relayForwardResponse(buffer, len);
                    continue;
                }

                // Check if this is a forwarded request (from another node)
                boolean isForwarded = isForwardedMessage(buffer, len);

                InetAddress originalClientAddress = null;
                int originalClientPort = 0;
                int hopCount = 0;
                int msgOffset = 0;

                if (isForwarded) {
                    // Extract original client IP, port, and hop count from forward header
                    originalClientAddress = InetAddress.getByAddress(new byte[]{
                            buffer[4], buffer[5], buffer[6], buffer[7]
                    });
                    originalClientPort = ((buffer[8] & 0xFF) << 24)
                            | ((buffer[9] & 0xFF) << 16)
                            | ((buffer[10] & 0xFF) << 8)
                            | (buffer[11] & 0xFF);
                    hopCount = buffer[12] & 0xFF;
                    msgOffset = FORWARD_HEADER_SIZE;
                }

                // Parse protobuf
                Msg msg;
                try {
                    msg = Msg.parseFrom(ByteString.copyFrom(
                            buffer, msgOffset, len - msgOffset));
                } catch (InvalidProtocolBufferException e) {
                    continue;
                }

                // Route to worker
                ReceivedPacket received = new ReceivedPacket(
                        msg, packet, isForwarded, originalClientAddress, originalClientPort,
                        hopCount);

                int workerIndex = Math.abs(msg.getMessageID().hashCode() % NUM_WORKERS);
                Worker worker = workers[workerIndex];

                if (!worker.offer(received)) {
                    if (!verifyChecksum(msg)) {
                        continue;
                    }
                    handleOverload(received, msg.getMessageID());
                }

            } catch (IOException e) {
                if (running) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * Relay a forward response directly to the original client.
     * Extracts client IP/port from the RESPONSE_MAGIC header and sends
     * the raw response (without the header) to the client.
     */
    private void relayForwardResponse(byte[] buffer, int length) {
        try {
            // Extract original client IP and port from header
            InetAddress clientAddress = InetAddress.getByAddress(new byte[]{
                    buffer[4], buffer[5], buffer[6], buffer[7]
            });
            int clientPort = ((buffer[8] & 0xFF) << 24)
                    | ((buffer[9] & 0xFF) << 16)
                    | ((buffer[10] & 0xFF) << 8)
                    | (buffer[11] & 0xFF);

            // Send the response payload (after the header) to the original client
            int payloadOffset = RESPONSE_HEADER_SIZE;
            int payloadLength = length - RESPONSE_HEADER_SIZE;

            DatagramPacket responsePacket = new DatagramPacket(
                    buffer, payloadOffset, payloadLength,
                    clientAddress, clientPort
            );
            socket.send(responsePacket);
        } catch (IOException e) {
            // Best effort
        }
    }

    /**
     * Handle an incoming gossip packet on the server receive thread.
     */
    private void handleGossipPacket(byte[] buffer, DatagramPacket packet) {
        try {
            GossipMessage msg = GossipMessage.deserialize(buffer, packet.getLength());
            if (msg != null) {
                gossipService.handleGossipMessage(msg, packet.getAddress(), packet.getPort());
            }
        } catch (Exception e) {
            System.err.println("Error handling gossip packet: " + e.getMessage());
        }
    }

    /**
     * Handle overload when worker queue is full.
     * For forwarded requests, the response must use RESPONSE_MAGIC so the
     * forwarding node can relay it to the original client.
     */
    private void handleOverload(ReceivedPacket packet, ByteString messageId) {
        try {
            System.err.println("[OVERLOAD-301] Queue full for msgId=" + messageId.hashCode());
            byte[] response = buildMsg(messageId, buildOverloadResponse(301));

            if (packet.isForwarded && packet.originalClientAddress != null) {
                // Send with RESPONSE_MAGIC header so forwarding node relays to client
                byte[] prefixed = new byte[RESPONSE_HEADER_SIZE + response.length];
                System.arraycopy(RESPONSE_MAGIC, 0, prefixed, 0, 4);
                byte[] clientIp = packet.originalClientAddress.getAddress();
                System.arraycopy(clientIp, 0, prefixed, 4, 4);
                int clientPort = packet.originalClientPort;
                prefixed[8] = (byte) (clientPort >> 24);
                prefixed[9] = (byte) (clientPort >> 16);
                prefixed[10] = (byte) (clientPort >> 8);
                prefixed[11] = (byte) clientPort;
                System.arraycopy(response, 0, prefixed, RESPONSE_HEADER_SIZE, response.length);

                DatagramPacket responsePacket = new DatagramPacket(
                        prefixed, prefixed.length,
                        packet.address, packet.port // Send to forwarding node
                );
                socket.send(responsePacket);
            } else {
                DatagramPacket responsePacket = new DatagramPacket(
                        response, response.length,
                        packet.address, packet.port
                );
                socket.send(responsePacket);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Check if a packet starts with the forwarding magic prefix.
     */
    private static boolean isForwardedMessage(byte[] data, int length) {
        if (length < FORWARD_HEADER_SIZE) return false;
        return data[0] == FORWARD_MAGIC[0]
                && data[1] == FORWARD_MAGIC[1]
                && data[2] == FORWARD_MAGIC[2]
                && data[3] == FORWARD_MAGIC[3];
    }

    /**
     * Check if a packet starts with the response magic prefix.
     */
    private static boolean isResponseMessage(byte[] data, int length) {
        if (length < RESPONSE_HEADER_SIZE) return false;
        return data[0] == RESPONSE_MAGIC[0]
                && data[1] == RESPONSE_MAGIC[1]
                && data[2] == RESPONSE_MAGIC[2]
                && data[3] == RESPONSE_MAGIC[3];
    }

    public void stop() {
        running = false;
        gossipService.stop();
        keyTransferService.stop();
        for (Worker worker : workers) {
            worker.shutdown();
        }
        socket.close();
    }
}
