package com.g20.CPEN431.A9.server;

import com.g20.CPEN431.A9.network.GossipService;
import com.g20.CPEN431.A9.network.KeyTransferService;
import com.g20.CPEN431.A9.network.ReceivedPacket;
import com.g20.CPEN431.A9.cache.DualResponseCache;
import com.g20.CPEN431.A9.network.Node;
import com.g20.CPEN431.A9.storage.KeyValueStore;

import ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest;
import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.concurrent.ArrayBlockingQueue;

import static com.g20.CPEN431.A9.Constants.*;
import static com.g20.CPEN431.A9.util.MessageUtils.*;

// This code was in part generated by an LLM.
public class Worker extends Thread {
    private final ArrayBlockingQueue<ReceivedPacket> queue;
    private final DualResponseCache cache;
    private final DatagramSocket sendSocket;
    private final GossipService gossipService;
    private final KeyTransferService keyTransferService;
    private final Node selfNode;
    private volatile boolean running = true;

    public Worker(int id, DatagramSocket socket, GossipService gossipService,
                  KeyTransferService keyTransferService, Node selfNode) throws SocketException {
        super("Worker-" + id);
        this.queue = new ArrayBlockingQueue<>(QUEUE_SIZE_PER_WORKER);
        this.cache = new DualResponseCache(MAX_CACHE_ENTRIES_PER_WORKER / 2, CACHE_CLEANUP_INTERVAL_MS);
        this.sendSocket = socket;
        this.gossipService = gossipService;
        this.keyTransferService = keyTransferService;
        this.selfNode = selfNode;
    }

    public boolean offer(ReceivedPacket packet) {
        return queue.offer(packet);
    }

    public void shutdown() {
        running = false;
        this.interrupt();
    }

    @Override
    public void run() {
        while (running) {
            try {
                ReceivedPacket packet = queue.take();
                handleRequest(packet);
            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void handleRequest(ReceivedPacket packet) {
        try {
            Msg msg = packet.msg;

            if (!verifyChecksum(msg)) return;

            ByteString messageId = msg.getMessageID();
            byte[] messageIdBytes = messageId.toByteArray();

            KVRequest request;
            try {
                request = KVRequest.parseFrom(msg.getPayload());
            } catch (InvalidProtocolBufferException e) {
                sendResponse(packet, buildMsg(messageId, buildKVResponse(ERR_INTERNAL_FAILURE)));
                return;
            }

            int command = request.getCommand();

            // Node-local commands: always process locally
            if (command == CMD_SHUTDOWN || command == CMD_WIPEOUT
                    || command == CMD_IS_ALIVE || command == CMD_GET_PID
                    || command == CMD_GET_MEMBERSHIP_COUNT) {
                processLocally(packet, msg, request, command, messageId, messageIdBytes);
                return;
            }

            // During gossip warmup, drop KV requests — ring hasn't stabilized yet.
            // Clients will retry after the brief warmup period (~600ms).
            if (!gossipService.isRingStable()) {
                return;
            }

            // For PUT, GET, REMOVE: check ring ownership
            if (request.hasKey() && !request.getKey().isEmpty()) {
                ByteString key = request.getKey();
                Node responsible = gossipService.getHashRing().getNodeForKey(key);

                if (responsible != null && responsible.id != selfNode.id) {
                    // Ring says another node owns this key.

                    // Loop-breaking rule: if the sender is a recovering node that we're
                    // actively transferring to, handle it here to avoid A→C→A loops.
                    if (packet.isForwarded
                            && keyTransferService.isActiveTransferTarget(responsible.id)
                            && packet.senderNodeId == responsible.id
                            && (command == CMD_GET || command == CMD_REMOVE)) {
                        if (KeyValueStore.containsKey(key)) {
                            // Tombstone REMOVE so transfer doesn't resurrect it
                            if (command == CMD_REMOVE) {
                                keyTransferService.markRemovedDuringRecovery(key);
                            }
                            processLocally(packet, msg, request, command, messageId, messageIdBytes);
                        } else {
                            // Key already transferred and deleted — tell client to retry.
                            // The recovering node (A) has the key by now.
                            sendResponse(packet, buildMsg(messageId, buildOverloadResponse(303)));
                        }
                        return;
                    }

                    if (packet.hopCount >= MAX_FORWARD_HOPS) {
                        // Drop — client will retry after gossip converges
                        return;
                    } else {
                        forwardWithHops(packet, msg, responsible);
                    }
                    return;
                }

                // We own this key. During recovery, handle GET/REMOVE misses.
                if ((command == CMD_GET || command == CMD_REMOVE)
                        && keyTransferService.isRecovering()
                        && !KeyValueStore.containsKey(key)) {

                    // Tombstone REMOVE so transfer doesn't resurrect it
                    if (command == CMD_REMOVE) {
                        keyTransferService.markRemovedDuringRecovery(key);
                    }

                    if (packet.hopCount < MAX_FORWARD_HOPS) {
                        Node recoverySource = keyTransferService.getRecoverySourceForKey(key);
                        if (recoverySource != null) {
                            forwardWithHops(packet, msg, recoverySource);
                            return;
                        }
                    }
                }
            }

            // We own this key (or no key) — process locally
            processLocally(packet, msg, request, command, messageId, messageIdBytes);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void processLocally(ReceivedPacket packet, Msg msg, KVRequest request,
                                int command, ByteString messageId, byte[] messageIdBytes) throws IOException {
        if (isMutableCommand(command)) {
            KVResponse cachedResponse = cache.getResponse(messageIdBytes, command);
            if (cachedResponse != null) {
                sendResponse(packet, buildMsg(messageId, cachedResponse));
                return;
            }

            if (!cache.hasSpaceFor(messageIdBytes)) {
                sendResponse(packet, buildMsg(messageId, buildOverloadResponse(302)));
                return;
            }

            KVResponse response = RequestHandler.processRequest(request, gossipService);
            cache.put(messageIdBytes, response);
            sendResponse(packet, buildMsg(messageId, response));
        } else {
            KVResponse response = RequestHandler.processRequest(request, gossipService);
            sendResponse(packet, buildMsg(messageId, response));
        }
    }

    /**
     * Forward with hop chain for stateless multi-hop response routing.
     *
     * Forward header:
     *   FORWARD_MAGIC(4) + clientIP(4) + clientPort(4) + hopCount(1) + senderNodeId(4)
     *   + hop_chain(hopCount * 8) + Msg
     *
     * Each forwarder appends its own IP:port to the hop chain. The response unwinds
     * through this chain: processor sends to last hop, each hop relays to the previous,
     * until the first hop relays to the client.
     */
    private void forwardWithHops(ReceivedPacket packet, Msg msg, Node target) {
        try {
            InetAddress clientAddr;
            int clientPort;
            int newHopCount;
            byte[] newHopChain;

            if (packet.isForwarded) {
                clientAddr = packet.originalClientAddress;
                clientPort = packet.originalClientPort;
                newHopCount = packet.hopCount + 1;
                // Append our own address to the existing hop chain
                newHopChain = new byte[newHopCount * HOP_ENTRY_SIZE];
                System.arraycopy(packet.hopChainBytes, 0, newHopChain, 0, packet.hopChainBytes.length);
                writeHopEntry(newHopChain, packet.hopChainBytes.length);
            } else {
                clientAddr = packet.address;
                clientPort = packet.port;
                newHopCount = 1;
                // Start hop chain with our own address
                newHopChain = new byte[HOP_ENTRY_SIZE];
                writeHopEntry(newHopChain, 0);
            }

            int headerSize = forwardHeaderSize(newHopCount);
            byte[] msgBytes = msg.toByteArray();
            byte[] forwardedBytes = new byte[headerSize + msgBytes.length];

            // FORWARD_MAGIC
            System.arraycopy(FORWARD_MAGIC, 0, forwardedBytes, 0, 4);

            // Client IP
            byte[] clientIp = clientAddr.getAddress();
            System.arraycopy(clientIp, 0, forwardedBytes, 4, 4);

            // Client port (big-endian)
            forwardedBytes[8] = (byte) (clientPort >> 24);
            forwardedBytes[9] = (byte) (clientPort >> 16);
            forwardedBytes[10] = (byte) (clientPort >> 8);
            forwardedBytes[11] = (byte) clientPort;

            // Hop count
            forwardedBytes[12] = (byte) newHopCount;

            // Sender node ID (this node's ID)
            forwardedBytes[13] = (byte) (selfNode.id >> 24);
            forwardedBytes[14] = (byte) (selfNode.id >> 16);
            forwardedBytes[15] = (byte) (selfNode.id >> 8);
            forwardedBytes[16] = (byte) selfNode.id;

            // Hop chain
            System.arraycopy(newHopChain, 0, forwardedBytes, FORWARD_HEADER_BASE_SIZE, newHopChain.length);

            // Msg payload
            System.arraycopy(msgBytes, 0, forwardedBytes, headerSize, msgBytes.length);

            sendSocket.send(new DatagramPacket(forwardedBytes, forwardedBytes.length,
                    target.ipaddress, target.port));
        } catch (IOException e) {
            // Best effort
        }
    }

    /**
     * Write this node's IP:port into a hop chain buffer at the given offset.
     */
    private void writeHopEntry(byte[] chain, int offset) {
        byte[] ip = selfNode.ipaddress.getAddress();
        System.arraycopy(ip, 0, chain, offset, 4);
        chain[offset + 4] = (byte) (selfNode.port >> 24);
        chain[offset + 5] = (byte) (selfNode.port >> 16);
        chain[offset + 6] = (byte) (selfNode.port >> 8);
        chain[offset + 7] = (byte) selfNode.port;
    }

    /**
     * Send response. For forwarded requests, builds RESPONSE_MAGIC header with
     * relay chain so the response routes back through the forwarding path.
     *
     * Response header:
     *   RESPONSE_MAGIC(4) + clientIP(4) + clientPort(4) + chainLen(1)
     *   + relay_chain(chainLen * 8) + response
     *
     * The relay chain = hop chain minus the last entry (since we already send
     * to packet.address, which is the last forwarder).
     */
    private void sendResponse(ReceivedPacket packet, byte[] response) throws IOException {
        if (packet.isForwarded && packet.originalClientAddress != null) {
            int chainLen = Math.max(0, packet.hopCount - 1);
            int headerSize = responseHeaderSize(chainLen);
            byte[] prefixed = new byte[headerSize + response.length];

            System.arraycopy(RESPONSE_MAGIC, 0, prefixed, 0, 4);

            byte[] clientIp = packet.originalClientAddress.getAddress();
            System.arraycopy(clientIp, 0, prefixed, 4, 4);

            int clientPort = packet.originalClientPort;
            prefixed[8] = (byte) (clientPort >> 24);
            prefixed[9] = (byte) (clientPort >> 16);
            prefixed[10] = (byte) (clientPort >> 8);
            prefixed[11] = (byte) clientPort;

            prefixed[12] = (byte) chainLen;

            // Relay chain: all hop entries except the last one
            if (chainLen > 0) {
                System.arraycopy(packet.hopChainBytes, 0, prefixed,
                        RESPONSE_HEADER_BASE_SIZE, chainLen * HOP_ENTRY_SIZE);
            }

            System.arraycopy(response, 0, prefixed, headerSize, response.length);

            sendSocket.send(new DatagramPacket(prefixed, prefixed.length,
                    packet.address, packet.port));
        } else {
            sendSocket.send(new DatagramPacket(response, response.length,
                    packet.address, packet.port));
        }
    }
}
