package com.g20.CPEN431.A9.server;

import com.g20.CPEN431.A9.network.GossipService;
import com.g20.CPEN431.A9.network.KeyTransferService;
import com.g20.CPEN431.A9.network.ReceivedPacket;
import com.g20.CPEN431.A9.cache.DualResponseCache;
import com.g20.CPEN431.A9.network.Node;
import com.g20.CPEN431.A9.storage.KeyValueStore;

import ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest;
import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.concurrent.ArrayBlockingQueue;

import static com.g20.CPEN431.A9.Constants.*;
import static com.g20.CPEN431.A9.util.MessageUtils.*;

// This code was in part generated by an LLM.
public class Worker extends Thread {
    private final ArrayBlockingQueue<ReceivedPacket> queue;
    private final DualResponseCache cache;
    private final DatagramSocket sendSocket;
    private final GossipService gossipService;
    private final KeyTransferService keyTransferService;
    private volatile boolean running = true;

    public Worker(int id, DatagramSocket socket, GossipService gossipService,
                  KeyTransferService keyTransferService) throws SocketException {
        super("Worker-" + id);
        this.queue = new ArrayBlockingQueue<>(QUEUE_SIZE_PER_WORKER);
        this.cache = new DualResponseCache(MAX_CACHE_ENTRIES_PER_WORKER / 2, CACHE_CLEANUP_INTERVAL_MS);
        this.sendSocket = socket;
        this.gossipService = gossipService;
        this.keyTransferService = keyTransferService;
    }

    public boolean offer(ReceivedPacket packet) {
        return queue.offer(packet);
    }

    public void shutdown() {
        running = false;
        this.interrupt();
    }

    @Override
    public void run() {
        while (running) {
            try {
                ReceivedPacket packet = queue.take();
                handleRequest(packet);
            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void handleRequest(ReceivedPacket packet) {
        try {
            Msg msg = packet.msg;

            if (!verifyChecksum(msg)) {
                return;
            }

            ByteString messageId = msg.getMessageID();
            byte[] messageIdBytes = messageId.toByteArray();

            KVRequest request;
            try {
                request = KVRequest.parseFrom(msg.getPayload());
            } catch (InvalidProtocolBufferException e) {
                byte[] errorResponse = buildMsg(messageId, buildKVResponse(ERR_INTERNAL_FAILURE));
                sendResponse(packet, errorResponse);
                return;
            }

            int command = request.getCommand();

            // Commands that are always handled locally (node-specific)
            if (command == CMD_SHUTDOWN || command == CMD_WIPEOUT
                    || command == CMD_IS_ALIVE || command == CMD_GET_PID
                    || command == CMD_GET_MEMBERSHIP_COUNT) {
                processLocally(packet, msg, request, command, messageId, messageIdBytes);
                return;
            }

            // For PUT, GET, REMOVE: check if we own this key
            if (request.hasKey() && !request.getKey().isEmpty()) {
                Node responsible = gossipService.getHashRing().getNodeForKey(request.getKey());

                if (responsible != null && responsible.id != gossipService.getSelfNode().id) {
                    if (packet.hopCount >= MAX_FORWARD_HOPS) {
                        // Max hops reached — process locally to prevent infinite loops
                        processLocally(packet, msg, request, command, messageId, messageIdBytes);
                    } else {
                        // Forward to the responsible node (works for both direct and forwarded)
                        forwardWithHops(packet, msg, responsible);
                    }
                    return;
                }
            }

            // During recovery: if this is a GET or REMOVE and the key is not in our store,
            // forward to the recovery source which may still hold the key
            if ((command == CMD_GET || command == CMD_REMOVE)
                    && keyTransferService.isRecovering()
                    && request.hasKey() && !KeyValueStore.containsKey(request.getKey())) {
                if (packet.hopCount < MAX_FORWARD_HOPS) {
                    Node recoverySource = keyTransferService.getRecoverySourceForKey(request.getKey());
                    if (recoverySource != null) {
                        forwardWithHops(packet, msg, recoverySource);
                        return;
                    }
                }
            }

            // We own this key (or no key provided) - process locally
            processLocally(packet, msg, request, command, messageId, messageIdBytes);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Process a request locally using the existing logic.
     */
    private void processLocally(ReceivedPacket packet, Msg msg, KVRequest request,
                                int command, ByteString messageId, byte[] messageIdBytes) throws IOException {
        if (isMutableCommand(command)) {
            // Check cache for duplicate request
            KVResponse cachedResponse = cache.getResponse(messageIdBytes, command);
            if (cachedResponse != null) {
                sendResponse(packet, buildMsg(messageId, cachedResponse));
                return;
            }

            // Check if there's space to cache before processing
            if (!cache.hasSpaceFor(messageIdBytes)) {
                System.err.println("[OVERLOAD-302] Cache full for msgId=" + messageId.hashCode());
                sendResponse(packet, buildMsg(messageId, buildOverloadResponse(302)));
                return;
            }

            // Process request
            KVResponse response = RequestHandler.processRequest(request, gossipService);

            // Cache the response
            cache.put(messageIdBytes, response);

            sendResponse(packet, buildMsg(messageId, response));
        } else {
            KVResponse response = RequestHandler.processRequest(request, gossipService);
            sendResponse(packet, buildMsg(messageId, response));
        }
    }

    /**
     * Unified forwarding method with hop count support.
     * For direct client requests (hopCount=0): uses packet sender as client info, sets hopCount=1.
     * For already-forwarded requests (hopCount>0): preserves original client info, increments hopCount.
     *
     * Header format: FORWARD_MAGIC(4) + clientIP(4) + clientPort(4) + hopCount(1) + Msg
     */
    private void forwardWithHops(ReceivedPacket packet, Msg msg, Node target) {
        try {
            // Determine client info and hop count
            InetAddress clientAddr;
            int clientPort;
            int newHopCount;

            if (packet.isForwarded) {
                // Preserve original client info from the forwarded packet
                clientAddr = packet.originalClientAddress;
                clientPort = packet.originalClientPort;
                newHopCount = packet.hopCount + 1;
            } else {
                // Direct client request — use packet sender as client
                clientAddr = packet.address;
                clientPort = packet.port;
                newHopCount = 1;
            }

            byte[] msgBytes = msg.toByteArray();
            byte[] forwardedBytes = new byte[FORWARD_HEADER_SIZE + msgBytes.length];

            // Magic
            System.arraycopy(FORWARD_MAGIC, 0, forwardedBytes, 0, 4);

            // Client IP (4 bytes)
            byte[] clientIp = clientAddr.getAddress();
            System.arraycopy(clientIp, 0, forwardedBytes, 4, 4);

            // Client port (4 bytes, big-endian)
            forwardedBytes[8] = (byte) (clientPort >> 24);
            forwardedBytes[9] = (byte) (clientPort >> 16);
            forwardedBytes[10] = (byte) (clientPort >> 8);
            forwardedBytes[11] = (byte) clientPort;

            // Hop count (1 byte)
            forwardedBytes[12] = (byte) newHopCount;

            // Msg payload
            System.arraycopy(msgBytes, 0, forwardedBytes, FORWARD_HEADER_SIZE, msgBytes.length);

            DatagramPacket forwardPacket = new DatagramPacket(
                    forwardedBytes, forwardedBytes.length,
                    target.ipaddress, target.port
            );
            sendSocket.send(forwardPacket);
        } catch (IOException e) {
            // Best effort — if send fails, client will retry
        }
    }

    /**
     * Send a response. For forwarded requests, prepend RESPONSE_MAGIC + client info
     * so the forwarding node can relay the response to the original client.
     */
    private void sendResponse(ReceivedPacket packet, byte[] response) throws IOException {
        if (packet.isForwarded && packet.originalClientAddress != null) {
            // Prepend RESPONSE_MAGIC + client IP + client port
            byte[] prefixed = new byte[RESPONSE_HEADER_SIZE + response.length];

            // Magic
            System.arraycopy(RESPONSE_MAGIC, 0, prefixed, 0, 4);

            // Original client IP (4 bytes)
            byte[] clientIp = packet.originalClientAddress.getAddress();
            System.arraycopy(clientIp, 0, prefixed, 4, 4);

            // Original client port (4 bytes, big-endian)
            int clientPort = packet.originalClientPort;
            prefixed[8] = (byte) (clientPort >> 24);
            prefixed[9] = (byte) (clientPort >> 16);
            prefixed[10] = (byte) (clientPort >> 8);
            prefixed[11] = (byte) clientPort;

            // Response payload
            System.arraycopy(response, 0, prefixed, RESPONSE_HEADER_SIZE, response.length);

            DatagramPacket responsePacket = new DatagramPacket(
                    prefixed, prefixed.length,
                    packet.address, packet.port // Send to forwarding node
            );
            sendSocket.send(responsePacket);
        } else {
            DatagramPacket responsePacket = new DatagramPacket(
                    response, response.length,
                    packet.address, packet.port
            );
            sendSocket.send(responsePacket);
        }
    }
}
