package com.g20.CPEN431.A9;

// This code was in part generated by an LLM.
public final class Constants {
    private Constants() {} // Prevent instantiation

    // Server configuration
    public static final int MAX_PACKET_SIZE = 16 * 1024;
    public static final int ESTIMATED_MAX_PACKET_SIZE = 11 * 1024; // Worst-case ReceivedPacket memory
    public static int NUM_WORKERS;
    public static int QUEUE_SIZE_PER_WORKER;
    public static int MAX_CACHE_ENTRIES_PER_WORKER;
    public static final long CACHE_TTL_MS = 2500;
    public static final long CACHE_CLEANUP_INTERVAL_MS = 1000;
    public static final int OVERLOAD_WAIT_TIME_MS = 300;

    // Error codes
    public static final int ERR_SUCCESS = 0x00;
    public static final int ERR_NON_EXISTENT_KEY = 0x01;
    public static final int ERR_OUT_OF_SPACE = 0x02;
    public static final int ERR_OVERLOAD = 0x03;
    public static final int ERR_INTERNAL_FAILURE = 0x04;
    public static final int ERR_UNKNOWN_COMMAND = 0x05;
    public static final int ERR_INVALID_KEY = 0x06;
    public static final int ERR_INVALID_VALUE = 0x07;

    // Command codes
    public static final int CMD_PUT = 0x01;
    public static final int CMD_GET = 0x02;
    public static final int CMD_REMOVE = 0x03;
    public static final int CMD_SHUTDOWN = 0x04;
    public static final int CMD_WIPEOUT = 0x05;
    public static final int CMD_IS_ALIVE = 0x06;
    public static final int CMD_GET_PID = 0x07;
    public static final int CMD_GET_MEMBERSHIP_COUNT = 0x08;

    // Limits
    public static final int MAX_KEY_LENGTH = 32;
    public static final int MAX_VALUE_LENGTH = 10000;

    // Memory budget calculation
    public static long QUEUE_MEMORY;
    public static final long CACHE_ENTRY_SIZE = 18;
    public static long CACHE_MEMORY;
    public static final long JVM_OVERHEAD = 2 * 1024 * 1024;
    public static final long OPERATIONAL_RESERVE = 2 * 1024 * 1024;
    public static long MEMORY_THRESHOLD_BYTES;

    /**
     * Initialize worker count and derived constants based on co-located node count.
     * Must be called before creating the Server.
     *
     * @param nodesOnHost number of nodes sharing this host
     */
    public static void init(int nodesOnHost) {
        NUM_WORKERS = Math.max(1, Runtime.getRuntime().availableProcessors() / nodesOnHost);
        QUEUE_SIZE_PER_WORKER = 350 / NUM_WORKERS;
        MAX_CACHE_ENTRIES_PER_WORKER = 70000 / NUM_WORKERS;
        QUEUE_MEMORY = (long) NUM_WORKERS * QUEUE_SIZE_PER_WORKER * ESTIMATED_MAX_PACKET_SIZE;
        CACHE_MEMORY = (long) NUM_WORKERS * MAX_CACHE_ENTRIES_PER_WORKER * CACHE_ENTRY_SIZE;
        MEMORY_THRESHOLD_BYTES = QUEUE_MEMORY + CACHE_MEMORY + JVM_OVERHEAD + OPERATIONAL_RESERVE;
        System.out.println("Constants: " + nodesOnHost + " nodes on host, "
                + Runtime.getRuntime().availableProcessors() + " cores -> "
                + NUM_WORKERS + " workers");
    }

    // ========================
    // Gossip protocol settings
    // ========================

    /** How often to gossip with a random peer (ms) */
    public static final long GOSSIP_INTERVAL_MS = 200;

    /** How often to check for failed nodes (ms) */
    public static final long GOSSIP_FAILURE_CHECK_INTERVAL_MS = 500;

    /** Time without heartbeat update before marking a node as failed (ms) */
    public static final long GOSSIP_T_FAIL_MS = 3000;

    /** Time after failure before removing a node from the membership list entirely (ms).
     *  Must be > T_FAIL to allow failure info to propagate. */
    public static final long GOSSIP_T_CLEANUP_MS = 15000;

    /** Number of virtual nodes per physical node on the hash ring */
    public static final int VIRTUAL_NODES = 3;

    /** Magic bytes prefixed to forwarded UDP packets (A -> B).
     *  First byte 0xFF has wire-type 7 in protobuf, which is invalid —
     *  so no valid protobuf message can start with this prefix.
     *  Full forward header: FORWARD_MAGIC(4) + clientIP(4) + clientPort(4) + Msg */
    public static final byte[] FORWARD_MAGIC = {(byte) 0xFF, (byte) 0x72, (byte) 0x57, (byte) 0x44};

    /** Magic bytes prefixed to responses for forwarded requests (B -> A).
     *  Full response header: RESPONSE_MAGIC(4) + clientIP(4) + clientPort(4) + response Msg */
    public static final byte[] RESPONSE_MAGIC = {(byte) 0xFF, (byte) 0xA2, (byte) 0xB3, (byte) 0xC4};

    /** Size of the forward/response header: 4 (magic) + 4 (IP) + 4 (port) */
    public static final int FORWARD_HEADER_SIZE = 12;
    public static final int RESPONSE_HEADER_SIZE = 12;

    public static boolean isMutableCommand(int command) {
        return command == CMD_PUT || command == CMD_REMOVE ||
                command == CMD_WIPEOUT || command == CMD_GET_PID;
    }
}