package com.g20.CPEN431.A9;

// This code was in part generated by an LLM.
public final class Constants {
    private Constants() {} // Prevent instantiation

    // Server configuration
    public static final int MAX_PACKET_SIZE = 16 * 1024;
    public static final int ESTIMATED_MAX_PACKET_SIZE = 11 * 1024; // Worst-case ReceivedPacket memory
    public static int NUM_WORKERS;
    public static int QUEUE_SIZE_PER_WORKER;
    public static int MAX_CACHE_ENTRIES_PER_WORKER;
    public static final long CACHE_TTL_MS = 2500;
    public static final long CACHE_CLEANUP_INTERVAL_MS = 1000;
    public static final int OVERLOAD_WAIT_TIME_MS = 300;

    // Error codes
    public static final int ERR_SUCCESS = 0x00;
    public static final int ERR_NON_EXISTENT_KEY = 0x01;
    public static final int ERR_OUT_OF_SPACE = 0x02;
    public static final int ERR_OVERLOAD = 0x03;
    public static final int ERR_INTERNAL_FAILURE = 0x04;
    public static final int ERR_UNKNOWN_COMMAND = 0x05;
    public static final int ERR_INVALID_KEY = 0x06;
    public static final int ERR_INVALID_VALUE = 0x07;

    // Command codes
    public static final int CMD_PUT = 0x01;
    public static final int CMD_GET = 0x02;
    public static final int CMD_REMOVE = 0x03;
    public static final int CMD_SHUTDOWN = 0x04;
    public static final int CMD_WIPEOUT = 0x05;
    public static final int CMD_IS_ALIVE = 0x06;
    public static final int CMD_GET_PID = 0x07;
    public static final int CMD_GET_MEMBERSHIP_COUNT = 0x08;

    // Limits
    public static final int MAX_KEY_LENGTH = 32;
    public static final int MAX_VALUE_LENGTH = 10000;

    // Memory budget calculation
    public static long QUEUE_MEMORY;
    public static final long CACHE_ENTRY_SIZE = 18;
    public static long CACHE_MEMORY;
    public static final long JVM_OVERHEAD = 2 * 1024 * 1024;
    public static final long OPERATIONAL_RESERVE = 2 * 1024 * 1024;
    public static long MEMORY_THRESHOLD_BYTES;

    /**
     * Initialize worker count and derived constants based on co-located node count.
     * Must be called before creating the Server.
     *
     * @param nodesOnHost number of nodes sharing this host
     */
    public static void init(int nodesOnHost) {
        NUM_WORKERS = Math.max(1, Runtime.getRuntime().availableProcessors() / nodesOnHost);
        QUEUE_SIZE_PER_WORKER = 350 / NUM_WORKERS;
        MAX_CACHE_ENTRIES_PER_WORKER = 70000 / NUM_WORKERS;
        QUEUE_MEMORY = (long) NUM_WORKERS * QUEUE_SIZE_PER_WORKER * ESTIMATED_MAX_PACKET_SIZE;
        CACHE_MEMORY = (long) NUM_WORKERS * MAX_CACHE_ENTRIES_PER_WORKER * CACHE_ENTRY_SIZE;
        MEMORY_THRESHOLD_BYTES = QUEUE_MEMORY + CACHE_MEMORY + JVM_OVERHEAD + OPERATIONAL_RESERVE;
        System.out.println("Constants: " + nodesOnHost + " nodes on host, "
                + Runtime.getRuntime().availableProcessors() + " cores -> "
                + NUM_WORKERS + " workers");
    }

    // ========================
    // Gossip protocol settings
    // ========================

    /** Number of random peers to gossip with each cycle */
    public static final int GOSSIP_FANOUT = 3;

    /** How often to gossip with a random peer (ms) */
    public static final long GOSSIP_INTERVAL_MS = 200;

    /** How often to check for failed nodes (ms) */
    public static final long GOSSIP_FAILURE_CHECK_INTERVAL_MS = 500;

    /** Minimum gossip cycles before the ring can be considered stable */
    public static final int GOSSIP_WARMUP_MIN_CYCLES = 5;

    /** Ring size must be unchanged for this many consecutive cycles to be considered stable */
    public static final int GOSSIP_WARMUP_STABLE_CYCLES = 3;

    /** Time without heartbeat update before marking a node as SUSPECT (ms) */
    public static final long GOSSIP_T_FAIL_MS = 3000;

    /** Time in SUSPECT state before confirming DEAD (ms).
     *  Gives the node a chance to refute via a fresh heartbeat. */
    public static final long GOSSIP_T_SUSPECT_MS = 2000;

    /** Time after failure before removing a node from the membership list entirely (ms).
     *  Must be > T_FAIL to allow failure info to propagate. */
    public static final long GOSSIP_T_CLEANUP_MS = 15000;

    /** Maximum gossip entries per message to stay within UDP MTU (~1400 bytes).
     *  Each entry is 29 bytes (includes 8-byte generation). Budget: (1400 - 13 header) / 29 ≈ 47 */
    public static final int GOSSIP_MAX_ENTRIES = 47;

    /** Number of virtual nodes per physical node on the hash ring */
    public static final int VIRTUAL_NODES = 3;

    /** Magic bytes prefixed to forwarded UDP packets (A -> B).
     *  First byte 0xFF has wire-type 7 in protobuf, which is invalid —
     *  so no valid protobuf message can start with this prefix.
     *  Full forward header: FORWARD_MAGIC(4) + clientIP(4) + clientPort(4) + Msg */
    public static final byte[] FORWARD_MAGIC = {(byte) 0xFF, (byte) 0x72, (byte) 0x57, (byte) 0x44};

    /** Magic bytes prefixed to responses for forwarded requests (B -> A).
     *  Full response header: RESPONSE_MAGIC(4) + clientIP(4) + clientPort(4) + response Msg */
    public static final byte[] RESPONSE_MAGIC = {(byte) 0xFF, (byte) 0xA2, (byte) 0xB3, (byte) 0xC4};

    /** Forward header base: 4 magic + 4 clientIP + 4 clientPort + 1 hopCount + 4 senderNodeId */
    public static final int FORWARD_HEADER_BASE_SIZE = 17;
    /** Response header base: 4 magic + 4 clientIP + 4 clientPort + 1 chainLen */
    public static final int RESPONSE_HEADER_BASE_SIZE = 13;
    /** Size of one hop entry in the chain: 4 IP + 4 port */
    public static final int HOP_ENTRY_SIZE = 8;

    /** Maximum number of forwarding hops before dropping the packet */
    public static final int MAX_FORWARD_HOPS = 10;

    public static int forwardHeaderSize(int hopCount) {
        return FORWARD_HEADER_BASE_SIZE + hopCount * HOP_ENTRY_SIZE;
    }

    public static int responseHeaderSize(int chainLen) {
        return RESPONSE_HEADER_BASE_SIZE + chainLen * HOP_ENTRY_SIZE;
    }

    // ========================
    // Key transfer protocol
    // ========================

    /** Magic bytes for key transfer data packets */
    public static final byte[] KEY_TRANSFER_MAGIC = {(byte) 0xFF, (byte) 0xD1, (byte) 0xE2, (byte) 0xF3};

    /** Magic bytes for transfer complete notification */
    public static final byte[] TRANSFER_COMPLETE_MAGIC = {(byte) 0xFF, (byte) 0xC1, (byte) 0xD2, (byte) 0xE3};

    /** Magic bytes for transfer ACK packets */
    public static final byte[] TRANSFER_ACK_MAGIC = {(byte) 0xFF, (byte) 0xB1, (byte) 0xC2, (byte) 0xD3};

    /** Transfer ACK size: 4 magic + 4 receiverId + 4 batchId */
    public static final int TRANSFER_ACK_SIZE = 12;

    /** Magic bytes for transfer pending notification (successor is recovering, will send soon) */
    public static final byte[] TRANSFER_PENDING_MAGIC = {(byte) 0xFF, (byte) 0xA1, (byte) 0xB2, (byte) 0xC3};

    /** Transfer pending size: 4 magic + 4 senderId */
    public static final int TRANSFER_PENDING_SIZE = 8;

    /** Maximum number of retries for unacknowledged transfer batches */
    public static final int MAX_TRANSFER_RETRIES = 3;

    /** Interval between transfer retry attempts (ms) */
    public static final long TRANSFER_RETRY_INTERVAL_MS = 1000;

    /** How long sender holds transferred keys before deleting (ms) */
    public static final long TRANSFER_HOLD_TIME_MS = 10_000;

    /** Delay before exiting recovery mode after transfer complete (ms) */
    public static final long RECOVERY_GRACE_PERIOD_MS = 3_000;

    /** Key transfer header: 4 magic + 4 senderId + 4 batchId + 2 numEntries */
    public static final int KEY_TRANSFER_HEADER_SIZE = 14;

    /** Transfer complete size: 4 magic + 4 senderId + 4 totalKeys */
    public static final int TRANSFER_COMPLETE_SIZE = 12;

    /** Timeout for awaiting-recovery state: if no transfer arrives, assume clean bootstrap */
    public static final long AWAITING_RECOVERY_TIMEOUT_MS = 15_000;

    // ========================
    // Pull-based key transfer
    // ========================

    /** Magic bytes for pull request packets (recovering node -> successor) */
    public static final byte[] PULL_REQUEST_MAGIC = {(byte) 0xFF, (byte) 0xE1, (byte) 0xF2, (byte) 0xA3};

    /** Pull request size: 4 magic + 4 senderId + 4 batchSeq */
    public static final int PULL_REQUEST_SIZE = 12;

    /** How often the pull loop sends pull requests (ms) */
    public static final long PULL_INTERVAL_MS = 200;

    /** Timeout for a pull request before re-sending (ms) */
    public static final long PULL_REQUEST_TIMEOUT_MS = 2000;

    /** Max retries for a pull request to a specific successor */
    public static final int MAX_PULL_RETRIES = 5;

    /** Timeout for stale pull server state (no request from predecessor) (ms) */
    public static final long PULL_CLIENT_TIMEOUT_MS = 30_000;

    public static boolean isMutableCommand(int command) {
        return command == CMD_PUT || command == CMD_REMOVE ||
                command == CMD_WIPEOUT;
    }
}