package com.g20.CPEN431.A9;

import com.g20.CPEN431.A9.server.Server;
import com.g20.CPEN431.A9.network.Node;

import java.io.BufferedReader;
import java.io.FileReader;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.ArrayList;
import java.util.List;

// This code was in part generated by an LLM.
public class Main {

    /** Pre-compute PID at startup (avoids slow lookups under NetEm) */
    public static final int PID = (int) ProcessHandle.current().pid();

    public static void main(String[] args) {
        if (args.length < 2) {
            System.err.println("Usage: java Main <port> <nodes-file> [--seed]");
            System.err.println("  nodes-file: one host:port per line (all known peers including self)");
            System.err.println("  --seed: skip key transfer and start directly in ACTIVE state");
            System.exit(1);
        }

        int port = Integer.parseInt(args[0]);
        String nodesFile = args[1];
        boolean isSeed = args.length >= 3 && "--seed".equals(args[2]);

        List<Node> allNodes = parseNodesFile(nodesFile, port);
        System.out.println("Loaded " + allNodes.size() + " nodes from " + nodesFile);

        Constants.init(allNodes.size());

        try {
            Server server = new Server(port, allNodes, isSeed);
            System.out.println("Server is running on port: " + port + " (PID: " + PID + ")"
                    + (isSeed ? " [SEED MODE]" : ""));
            server.start();
        } catch (SocketException e) {
            System.err.println("Failed to start server: " + e.getMessage());
            System.exit(1);
        }
    }

    /**
     * Parse a nodes file with lines of format: host:port
     * Assigns node IDs based on line order (0-indexed).
     */
    private static List<Node> parseNodesFile(String filename, int selfPort) {
        List<Node> nodes = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(filename))) {
            String line;
            int id = 0;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;

                String[] parts = line.split(":");
                if (parts.length != 2) {
                    System.err.println("Skipping malformed line: " + line);
                    continue;
                }

                String host = parts[0].trim();
                int nodePort = Integer.parseInt(parts[1].trim());
                InetAddress address = InetAddress.getByName(host);
                nodes.add(new Node(id, address, nodePort));
                id++;
            }
        } catch (Exception e) {
            System.err.println("Error reading nodes file: " + e.getMessage());
            System.exit(1);
        }
        return nodes;
    }
}