package com.g20.CPEN431.A9.util;

import static com.g20.CPEN431.A9.Constants.MEMORY_THRESHOLD_BYTES;

// This code was in part generated by an LLM.
public final class MemoryUtils {
    private static final Runtime runtime = Runtime.getRuntime();

    private MemoryUtils() {}

    /**
     * Returns available heap memory in bytes.
     * Available = maxMemory - (totalMemory - freeMemory)
     */
    public static long getAvailableMemory() {
        return runtime.maxMemory() - runtime.totalMemory() + runtime.freeMemory();
    }

    /**
     * Checks if there's enough memory to store additional data.
     * @param additionalBytes the size of data to be stored
     * @return true if memory is sufficient, false otherwise
     */
    public static boolean hasAvailableMemory(long additionalBytes) {
        return getAvailableMemory() > MEMORY_THRESHOLD_BYTES + additionalBytes;
    }
}
