package com.g20.CPEN431.A9.util;

import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;

import java.util.zip.CRC32;

import static com.g20.CPEN431.A9.Constants.*;

// This code was in part generated by an LLM.
public final class MessageUtils {
    private MessageUtils() {}

    // Pre-built static responses for common cases
    private static final KVResponse SUCCESS_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_SUCCESS)
            .build();
    private static final KVResponse NON_EXISTENT_KEY_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_NON_EXISTENT_KEY)
            .build();
    private static final KVResponse OUT_OF_SPACE_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_OUT_OF_SPACE)
            .build();
    private static final KVResponse OVERLOAD_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_OVERLOAD)
            .setOverloadWaitTime(OVERLOAD_WAIT_TIME_MS)
            .build();
    private static final KVResponse INTERNAL_FAILURE_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_INTERNAL_FAILURE)
            .build();
    private static final KVResponse UNKNOWN_COMMAND_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_UNKNOWN_COMMAND)
            .build();
    private static final KVResponse INVALID_KEY_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_INVALID_KEY)
            .build();
    private static final KVResponse INVALID_VALUE_RESPONSE = KVResponse.newBuilder()
            .setErrCode(ERR_INVALID_VALUE)
            .build();

    // ThreadLocal CRC32 to avoid allocating new instance per response
    private static final ThreadLocal<CRC32> CRC32_THREAD_LOCAL = ThreadLocal.withInitial(CRC32::new);

    public static KVResponse buildKVResponse(int errCode) {
        switch (errCode) {
            case ERR_SUCCESS: return SUCCESS_RESPONSE;
            case ERR_NON_EXISTENT_KEY: return NON_EXISTENT_KEY_RESPONSE;
            case ERR_OUT_OF_SPACE: return OUT_OF_SPACE_RESPONSE;
            case ERR_OVERLOAD: return OVERLOAD_RESPONSE;
            case ERR_INTERNAL_FAILURE: return INTERNAL_FAILURE_RESPONSE;
            case ERR_UNKNOWN_COMMAND: return UNKNOWN_COMMAND_RESPONSE;
            case ERR_INVALID_KEY: return INVALID_KEY_RESPONSE;
            case ERR_INVALID_VALUE: return INVALID_VALUE_RESPONSE;
            default:
                return KVResponse.newBuilder()
                        .setErrCode(errCode)
                        .build();
        }
    }

    public static KVResponse buildKVResponse(int errCode, ByteString value, int version) {
        return KVResponse.newBuilder()
                .setErrCode(errCode)
                .setValue(value)
                .setVersion(version)
                .build();
    }

    public static KVResponse buildOverloadResponse() {
        return OVERLOAD_RESPONSE;
    }

    /**
     * Build an overload response with a custom wait time that encodes the source.
     *   301 = worker queue full (Server receive loop)
     *   302 = response cache full (Worker.processLocally)
     *   303 = forward timeout/failure (Worker.forwardRequestAsync)
     */
    public static KVResponse buildOverloadResponse(int waitTimeMs) {
        return KVResponse.newBuilder()
                .setErrCode(ERR_OVERLOAD)
                .setOverloadWaitTime(waitTimeMs)
                .build();
    }

    public static KVResponse buildOutOfSpaceResponse() {
        return OUT_OF_SPACE_RESPONSE;
    }

    public static byte[] buildMsg(ByteString messageId, KVResponse kvResponse) {
        ByteString payload = kvResponse.toByteString();
        long checksum = computeChecksum(messageId, payload);

        return Msg.newBuilder()
                .setMessageID(messageId)
                .setPayload(payload)
                .setCheckSum(checksum)
                .build()
                .toByteArray();
    }

    private static long computeChecksum(ByteString messageId, ByteString payload) {
        CRC32 crc = CRC32_THREAD_LOCAL.get();
        crc.reset();
        crc.update(messageId.asReadOnlyByteBuffer());
        crc.update(payload.asReadOnlyByteBuffer());
        return crc.getValue();
    }

    public static boolean verifyChecksum(Msg msg) {
        long expected = computeChecksum(msg.getMessageID(), msg.getPayload());
        return expected == msg.getCheckSum();
    }
}