package com.s26615161.CPEN431.A4;

import static com.s26615161.CPEN431.A4.Constants.CACHE_TTL_MS;

// This code was in part generated by an LLM.
public class CachedResponse {
    public final byte[] response;
    public final long timestamp;

    public CachedResponse(byte[] response) {
        this.response = response;
        this.timestamp = System.currentTimeMillis();
    }

    public boolean isExpired() {
        return System.currentTimeMillis() - timestamp > CACHE_TTL_MS;
    }
}
