package com.s26615161.CPEN431.A4;

// This code was in part generated by an LLM.
public final class Constants {
    private Constants() {} // Prevent instantiation

    // Server configuration
    public static final int MAX_PACKET_SIZE = 16 * 1024;
    public static final int ESTIMATED_MAX_PACKET_SIZE = 11 * 1024; // Worst-case ReceivedPacket memory
    public static final int NUM_WORKERS = Runtime.getRuntime().availableProcessors();
    public static final int QUEUE_SIZE_PER_WORKER = 350 / NUM_WORKERS;
    public static final int MAX_CACHE_ENTRIES_PER_WORKER = 70000 / NUM_WORKERS;
    public static final long CACHE_TTL_MS = 2500;
    public static final long CACHE_CLEANUP_INTERVAL_MS = 1000;
    public static final int OVERLOAD_WAIT_TIME_MS = 300;

    // Error codes
    public static final int ERR_SUCCESS = 0x00;
    public static final int ERR_NON_EXISTENT_KEY = 0x01;
    public static final int ERR_OUT_OF_SPACE = 0x02;
    public static final int ERR_OVERLOAD = 0x03;
    public static final int ERR_INTERNAL_FAILURE = 0x04;
    public static final int ERR_UNKNOWN_COMMAND = 0x05;
    public static final int ERR_INVALID_KEY = 0x06;
    public static final int ERR_INVALID_VALUE = 0x07;

    // Command codes
    public static final int CMD_PUT = 0x01;
    public static final int CMD_GET = 0x02;
    public static final int CMD_REMOVE = 0x03;
    public static final int CMD_SHUTDOWN = 0x04;
    public static final int CMD_WIPEOUT = 0x05;
    public static final int CMD_IS_ALIVE = 0x06;
    public static final int CMD_GET_PID = 0x07;
    public static final int CMD_GET_MEMBERSHIP_COUNT = 0x08;

    // Limits
    public static final int MAX_KEY_LENGTH = 32;
    public static final int MAX_VALUE_LENGTH = 10000;

    // Memory budget calculation
    public static final long QUEUE_MEMORY = (long) NUM_WORKERS * QUEUE_SIZE_PER_WORKER * ESTIMATED_MAX_PACKET_SIZE;
    public static final long CACHE_ENTRY_SIZE = 18;
    public static final long CACHE_MEMORY = (long) NUM_WORKERS * MAX_CACHE_ENTRIES_PER_WORKER * CACHE_ENTRY_SIZE;
    public static final long JVM_OVERHEAD = 2 * 1024 * 1024;
    public static final long OPERATIONAL_RESERVE = 2 * 1024 * 1024;
    public static final long MEMORY_THRESHOLD_BYTES = QUEUE_MEMORY + CACHE_MEMORY + JVM_OVERHEAD + OPERATIONAL_RESERVE;

    public static boolean isMutableCommand(int command) {
        return command == CMD_PUT || command == CMD_REMOVE ||
               command == CMD_WIPEOUT || command == CMD_GET_PID;
    }
}
