package com.s26615161.CPEN431.A4;

import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;

import static com.s26615161.CPEN431.A4.Constants.*;

/**
 * Wrapper for two ResponseCache instances that alternates between them.
 * Every configured interval, swaps which cache is being written to and wipes the old one.
 * Reads search both caches. Not thread-safe - designed for single-threaded worker use.
 */
// This code was in part generated by an LLM.
public class DualResponseCache {
    private final int cacheCapacity;
    private final long swapIntervalMs;
    private final ResponseCache[] caches;
    private int currentWriteIndex;
    private long lastSwapTime;

    /**
     * Creates a dual cache with the specified capacity per cache and swap interval.
     * @param cacheCapacity number of entries each cache can hold
     * @param swapIntervalMs milliseconds between cache swaps
     */
    public DualResponseCache(int cacheCapacity, long swapIntervalMs) {
        this.cacheCapacity = cacheCapacity;
        this.swapIntervalMs = swapIntervalMs;
        this.caches = new ResponseCache[2];
        this.caches[0] = new ResponseCache(cacheCapacity);
        this.caches[1] = new ResponseCache(cacheCapacity);
        this.currentWriteIndex = 0;
        this.lastSwapTime = System.currentTimeMillis();
    }

    /**
     * Checks if it's time to swap caches and performs the swap if needed.
     * Call this periodically (e.g., before each put operation).
     */
    public void checkAndSwap() {
        long now = System.currentTimeMillis();
        if (now - lastSwapTime >= swapIntervalMs) {
            // Swap to the other cache
            currentWriteIndex = 1 - currentWriteIndex;
            // Wipe the cache we're now writing to
            caches[currentWriteIndex].wipe();
            lastSwapTime = now;
        }
    }

    /**
     * Checks if there is space to store an entry for the given key.
     * Performs swap check first, then checks the current write cache.
     * @param key the message ID bytes
     * @return true if the key can be stored, false otherwise
     */
    public boolean hasSpaceFor(byte[] key) {
        checkAndSwap();
        return caches[currentWriteIndex].hasSpaceFor(key);
    }

    /**
     * Stores a KVResponse in the current write cache.
     * Extracts errCode and the relevant second integer based on response type.
     * @param key the message ID bytes
     * @param response the KVResponse to cache
     * @return true if stored successfully, false if cache is full
     * @throws IllegalArgumentException if the response contains a value (GET success) which cannot be cached
     */
    public boolean put(byte[] key, KVResponse response) {

        int errCode = response.getErrCode();
        int secondValue = 0;

        // Determine what to store based on response content
        if (response.hasValue()) {
            // GET success response with value - cannot cache in two ints
            throw new IllegalArgumentException(
                "Cannot cache response with value field - GET success responses require full byte storage");
        }

        if (response.hasPid()) {
            secondValue = response.getPid();
        } else if (response.hasMembershipCount()) {
            secondValue = response.getMembershipCount();
        } else if (response.hasOverloadWaitTime()) {
            secondValue = response.getOverloadWaitTime();
        } else if (response.hasVersion()) {
            // Version without value shouldn't happen, but handle it
            secondValue = response.getVersion();
        }

        return caches[currentWriteIndex].put(key, errCode, secondValue);
    }

    /**
     * Retrieves cached response data for the given key.
     * Searches both caches (current write cache first, then the other).
     * @param key the message ID bytes
     * @return int array [errCode, secondValue] or null if not found
     */
    public int[] get(byte[] key) {
        // Search current write cache first (more likely to have recent entries)
        int[] result = caches[currentWriteIndex].get(key);
        if (result != null) {
            return result;
        }
        // Search the other cache
        return caches[1 - currentWriteIndex].get(key);
    }

    /**
     * Reconstructs a KVResponse from cached data.
     * @param key the message ID bytes
     * @param command the original command code (needed to determine response type)
     * @return the reconstructed KVResponse, or null if not in cache
     */
    public KVResponse getResponse(byte[] key, int command) {
        int[] cached = get(key);
        if (cached == null) {
            return null;
        }

        int errCode = cached[0];
        int secondValue = cached[1];

        KVResponse.Builder builder = KVResponse.newBuilder().setErrCode(errCode);

        // Add the appropriate field based on command type
        switch (command) {
            case CMD_GET_PID:
                if (errCode == ERR_SUCCESS) {
                    builder.setPid(secondValue);
                }
                break;
            case CMD_GET_MEMBERSHIP_COUNT:
                if (errCode == ERR_SUCCESS) {
                    builder.setMembershipCount(secondValue);
                }
                break;
            default:
                // For overload responses, add the wait time
                if (errCode == ERR_OVERLOAD && secondValue > 0) {
                    builder.setOverloadWaitTime(secondValue);
                }
                break;
        }

        return builder.build();
    }

    /**
     * Forces a swap and wipe of the current cache regardless of time elapsed.
     */
    public void forceSwap() {
        currentWriteIndex = 1 - currentWriteIndex;
        caches[currentWriteIndex].wipe();
        lastSwapTime = System.currentTimeMillis();
    }

    /**
     * Wipes both caches by creating new instances.
     */
    public void wipeAll() {
        caches[0].wipe();
        caches[1].wipe();
        lastSwapTime = System.currentTimeMillis();
    }

    /**
     * Returns the total storage size in bytes for both caches.
     */
    public int getTotalStorageSize() {
        return caches[0].getStorageSize() + caches[1].getStorageSize();
    }

    /**
     * Returns the capacity of each individual cache.
     */
    public int getCacheCapacity() {
        return cacheCapacity;
    }

    /**
     * Returns the swap interval in milliseconds.
     */
    public long getSwapIntervalMs() {
        return swapIntervalMs;
    }
}
