package com.g20.CPEN431.A7.cache;

import com.g20.CPEN431.A7.cache.ResponseCache;

import java.util.concurrent.locks.ReentrantReadWriteLock;

/**
 * A fixed-length concurrency-proof cache that stores two integers indexed by a bytestring key.
 * Uses a single byte[] array as storage with striped read-write locks for thread safety.
 * Each lock protects a bucket; linear probing occurs only within a bucket.
 * Values 21+ in the first integer are reserved as special codes.
 */
// This code was in part generated by an LLM.
public class ConcurrentResponseCache {
    // Entry layout: 8 bytes hash + 4 bytes value1 + 4 bytes value2 + 8 bytes timestamp = 24 bytes
    private static final int ENTRY_SIZE = 24;
    private static final int HASH_SIZE = 8;
    private static final int INT_SIZE = 4;
    private static final int TIMESTAMP_SIZE = 8;
    private static final int TIMESTAMP_OFFSET = HASH_SIZE + INT_SIZE + INT_SIZE;

    // Empty slot marker (hash value of 0 means empty)
    private static final long EMPTY_HASH = 0L;
    // Tombstone marker for deleted entries (preserves probe chains)
    private static final long TOMBSTONE_HASH = 1L;

    private final byte[] storage;
    private final int numBuckets;
    private final int bucketSize;  // entries per bucket
    private final ReentrantReadWriteLock[] locks;
    private final int[] tombstoneCounts;  // per-bucket tombstone count
    private final int tombstoneThreshold; // reset bucket if tombstones exceed this

    /**
     * Creates a cache with the specified number of buckets and entries per bucket.
     * @param numBuckets the number of buckets (each with its own lock)
     * @param bucketSize the number of entries per bucket
     */
    public ConcurrentResponseCache(int numBuckets, int bucketSize) {
        this.numBuckets = numBuckets;
        this.bucketSize = bucketSize;
        this.storage = new byte[numBuckets * bucketSize * ENTRY_SIZE];
        this.locks = new ReentrantReadWriteLock[numBuckets];
        this.tombstoneCounts = new int[numBuckets];
        // Reset bucket if more than half the entries are tombstones
        this.tombstoneThreshold = bucketSize / 2;
        for (int i = 0; i < numBuckets; i++) {
            locks[i] = new ReentrantReadWriteLock();
        }
    }

    /**
     * Computes a 64-bit FNV-1a hash of the key.
     * Ensures the result is never 0 or 1 (reserved for empty/tombstone).
     */
    private long computeHash(byte[] key) {
        long hash = 0xcbf29ce484222325L;
        for (byte b : key) {
            hash ^= (b & 0xff);
            hash *= 0x100000001b3L;
        }
        // Ensure hash is never 0 or 1 (reserved markers)
        if (hash == EMPTY_HASH || hash == TOMBSTONE_HASH) {
            return 2L;
        }
        return hash;
    }

    /**
     * Maps a hash to a bucket index.
     */
    private int getBucket(long hash) {
        return (int) ((hash & 0x7fffffffffffffffL) % numBuckets);
    }

    /**
     * Maps a hash to a starting slot index within a bucket.
     */
    private int getSlotInBucket(long hash) {
        // Use upper bits for intra-bucket index to get different distribution
        return (int) (((hash >>> 32) & 0x7fffffffL) % bucketSize);
    }

    /**
     * Gets the byte offset for the start of a bucket.
     */
    private int getBucketOffset(int bucket) {
        return bucket * bucketSize * ENTRY_SIZE;
    }

    /**
     * Writes a long value to the storage array at the specified offset.
     */
    private void writeLong(int offset, long value) {
        storage[offset]     = (byte) (value >>> 56);
        storage[offset + 1] = (byte) (value >>> 48);
        storage[offset + 2] = (byte) (value >>> 40);
        storage[offset + 3] = (byte) (value >>> 32);
        storage[offset + 4] = (byte) (value >>> 24);
        storage[offset + 5] = (byte) (value >>> 16);
        storage[offset + 6] = (byte) (value >>> 8);
        storage[offset + 7] = (byte) value;
    }

    /**
     * Reads a long value from the storage array at the specified offset.
     */
    private long readLong(int offset) {
        return ((long) (storage[offset] & 0xff) << 56)
             | ((long) (storage[offset + 1] & 0xff) << 48)
             | ((long) (storage[offset + 2] & 0xff) << 40)
             | ((long) (storage[offset + 3] & 0xff) << 32)
             | ((long) (storage[offset + 4] & 0xff) << 24)
             | ((long) (storage[offset + 5] & 0xff) << 16)
             | ((long) (storage[offset + 6] & 0xff) << 8)
             | ((long) (storage[offset + 7] & 0xff));
    }

    /**
     * Writes an int value to the storage array at the specified offset.
     */
    private void writeInt(int offset, int value) {
        storage[offset]     = (byte) (value >>> 24);
        storage[offset + 1] = (byte) (value >>> 16);
        storage[offset + 2] = (byte) (value >>> 8);
        storage[offset + 3] = (byte) value;
    }

    /**
     * Reads an int value from the storage array at the specified offset.
     */
    private int readInt(int offset) {
        return ((storage[offset] & 0xff) << 24)
             | ((storage[offset + 1] & 0xff) << 16)
             | ((storage[offset + 2] & 0xff) << 8)
             | (storage[offset + 3] & 0xff);
    }

    /**
     * Stores two integers in the cache indexed by the given key.
     * Uses hash to find starting slot, then linear probing within the bucket.
     * @param key the bytestring key
     * @param value1 the first integer
     * @param value2 the second integer
     * @return true if stored successfully, false if bucket is full
     */
    public boolean put(byte[] key, int value1, int value2) {
        long hash = computeHash(key);
        int bucket = getBucket(hash);
        int bucketOffset = getBucketOffset(bucket);
        int startSlot = getSlotInBucket(hash);

        ReentrantReadWriteLock lock = locks[bucket];
        lock.writeLock().lock();
        try {
            int firstTombstone = -1;  // Track first tombstone for reuse

            for (int i = 0; i < bucketSize; i++) {
                int slot = (startSlot + i) % bucketSize;
                int offset = bucketOffset + slot * ENTRY_SIZE;
                long storedHash = readLong(offset);

                if (storedHash == EMPTY_HASH) {
                    // Empty slot - use first tombstone if found, otherwise use this slot
                    int insertOffset;
                    if (firstTombstone >= 0) {
                        insertOffset = bucketOffset + firstTombstone * ENTRY_SIZE;
                        tombstoneCounts[bucket]--;
                    } else {
                        insertOffset = offset;
                    }
                    writeLong(insertOffset, hash);
                    writeInt(insertOffset + HASH_SIZE, value1);
                    writeInt(insertOffset + HASH_SIZE + INT_SIZE, value2);
                    writeLong(insertOffset + TIMESTAMP_OFFSET, System.currentTimeMillis());
                    return true;
                }
                if (storedHash == TOMBSTONE_HASH) {
                    // Remember first tombstone for potential reuse
                    if (firstTombstone < 0) {
                        firstTombstone = slot;
                    }
                    continue;
                }
                if (storedHash == hash) {
                    // Same key - update in place (keep original timestamp)
                    writeInt(offset + HASH_SIZE, value1);
                    writeInt(offset + HASH_SIZE + INT_SIZE, value2);
                    return true;
                }
            }

            // Bucket full but may have tombstones
            if (firstTombstone >= 0) {
                int offset = bucketOffset + firstTombstone * ENTRY_SIZE;
                tombstoneCounts[bucket]--;
                writeLong(offset, hash);
                writeInt(offset + HASH_SIZE, value1);
                writeInt(offset + HASH_SIZE + INT_SIZE, value2);
                writeLong(offset + TIMESTAMP_OFFSET, System.currentTimeMillis());
                return true;
            }

            // Bucket is completely full
            return false;
        } finally {
            lock.writeLock().unlock();
        }
    }

    /**
     * Stores a single integer in the cache indexed by the given key.
     * The second integer is set to 0.
     * @param key the bytestring key
     * @param value the integer to store
     * @return true if stored successfully, false if bucket is full
     */
    public boolean put(byte[] key, int value) {
        return put(key, value, 0);
    }

    /**
     * Retrieves the two integers associated with the given key.
     * Uses hash to find starting slot, then linear probing within the bucket.
     * @param key the bytestring key
     * @return an int array of length 2 containing the values, or null if not found
     */
    public int[] get(byte[] key) {
        long hash = computeHash(key);
        int bucket = getBucket(hash);
        int bucketOffset = getBucketOffset(bucket);
        int startSlot = getSlotInBucket(hash);

        ReentrantReadWriteLock lock = locks[bucket];
        lock.readLock().lock();
        try {
            for (int i = 0; i < bucketSize; i++) {
                int slot = (startSlot + i) % bucketSize;
                int offset = bucketOffset + slot * ENTRY_SIZE;
                long storedHash = readLong(offset);

                if (storedHash == EMPTY_HASH) {
                    // Empty slot - key not in bucket
                    return null;
                }
                if (storedHash == TOMBSTONE_HASH) {
                    // Skip tombstones
                    continue;
                }
                if (storedHash == hash) {
                    // Found the key
                    int value1 = readInt(offset + HASH_SIZE);
                    int value2 = readInt(offset + HASH_SIZE + INT_SIZE);
                    return new int[] { value1, value2 };
                }
            }
            // Searched entire bucket - not found
            return null;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Retrieves the two integers and creation timestamp associated with the given key.
     * Uses hash to find starting slot, then linear probing within the bucket.
     * @param key the bytestring key
     * @return a long array [value1, value2, timestamp], or null if not found
     */
    public long[] getWithTimestamp(byte[] key) {
        long hash = computeHash(key);
        int bucket = getBucket(hash);
        int bucketOffset = getBucketOffset(bucket);
        int startSlot = getSlotInBucket(hash);

        ReentrantReadWriteLock lock = locks[bucket];
        lock.readLock().lock();
        try {
            for (int i = 0; i < bucketSize; i++) {
                int slot = (startSlot + i) % bucketSize;
                int offset = bucketOffset + slot * ENTRY_SIZE;
                long storedHash = readLong(offset);

                if (storedHash == EMPTY_HASH) {
                    return null;
                }
                if (storedHash == TOMBSTONE_HASH) {
                    continue;
                }
                if (storedHash == hash) {
                    int value1 = readInt(offset + HASH_SIZE);
                    int value2 = readInt(offset + HASH_SIZE + INT_SIZE);
                    long timestamp = readLong(offset + TIMESTAMP_OFFSET);
                    return new long[] { value1, value2, timestamp };
                }
            }
            return null;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Checks if the cache contains an entry for the given key.
     * @param key the bytestring key
     * @return true if the key is in the cache, false otherwise
     */
    public boolean contains(byte[] key) {
        long hash = computeHash(key);
        int bucket = getBucket(hash);
        int bucketOffset = getBucketOffset(bucket);
        int startSlot = getSlotInBucket(hash);

        ReentrantReadWriteLock lock = locks[bucket];
        lock.readLock().lock();
        try {
            for (int i = 0; i < bucketSize; i++) {
                int slot = (startSlot + i) % bucketSize;
                int offset = bucketOffset + slot * ENTRY_SIZE;
                long storedHash = readLong(offset);

                if (storedHash == EMPTY_HASH) {
                    return false;
                }
                if (storedHash == TOMBSTONE_HASH) {
                    continue;
                }
                if (storedHash == hash) {
                    return true;
                }
            }
            return false;
        } finally {
            lock.readLock().unlock();
        }
    }

    /**
     * Removes an entry from the cache.
     * Uses hash to find starting slot, then linear probing within the bucket.
     * @param key the bytestring key
     * @return true if the key was found and removed, false if not found
     */
    public boolean remove(byte[] key) {
        long hash = computeHash(key);
        int bucket = getBucket(hash);
        int bucketOffset = getBucketOffset(bucket);
        int startSlot = getSlotInBucket(hash);

        ReentrantReadWriteLock lock = locks[bucket];
        lock.writeLock().lock();
        try {
            for (int i = 0; i < bucketSize; i++) {
                int slot = (startSlot + i) % bucketSize;
                int offset = bucketOffset + slot * ENTRY_SIZE;
                long storedHash = readLong(offset);

                if (storedHash == EMPTY_HASH) {
                    // Empty slot - key not in bucket
                    return false;
                }
                if (storedHash == TOMBSTONE_HASH) {
                    // Skip tombstones
                    continue;
                }
                if (storedHash == hash) {
                    // Found the key - mark as tombstone
                    writeLong(offset, TOMBSTONE_HASH);
                    tombstoneCounts[bucket]++;
                    return true;
                }
            }
            // Searched entire bucket - not found
            return false;
        } finally {
            lock.writeLock().unlock();
        }
    }

    /**
     * Expires all entries older than the specified cutoff time.
     * If a bucket has too many tombstones, it will be completely reset (compacted).
     * @param cutoffTime entries with timestamp before this will be removed
     * @return the number of entries expired
     */
    public int expireOlderThan(long cutoffTime) {
        int expiredCount = 0;

        for (int bucket = 0; bucket < numBuckets; bucket++) {
            ReentrantReadWriteLock lock = locks[bucket];
            lock.writeLock().lock();
            try {
                int bucketOffset = getBucketOffset(bucket);

                // Check if we should reset/compact this bucket
                if (tombstoneCounts[bucket] > tombstoneThreshold) {
                    expiredCount += compactBucket(bucket, bucketOffset, cutoffTime);
                } else {
                    expiredCount += expireBucketEntries(bucket, bucketOffset, cutoffTime);
                }
            } finally {
                lock.writeLock().unlock();
            }
        }

        return expiredCount;
    }

    /**
     * Expires old entries in a bucket by marking them as tombstones.
     * Called when tombstone count is below threshold.
     */
    private int expireBucketEntries(int bucket, int bucketOffset, long cutoffTime) {
        int expiredCount = 0;

        for (int i = 0; i < bucketSize; i++) {
            int offset = bucketOffset + i * ENTRY_SIZE;
            long storedHash = readLong(offset);

            if (storedHash == EMPTY_HASH || storedHash == TOMBSTONE_HASH) {
                continue;
            }

            long timestamp = readLong(offset + TIMESTAMP_OFFSET);
            if (timestamp < cutoffTime) {
                writeLong(offset, TOMBSTONE_HASH);
                tombstoneCounts[bucket]++;
                expiredCount++;
            }
        }

        return expiredCount;
    }

    /**
     * Compacts a bucket by keeping only valid, non-expired entries.
     * Removes all tombstones and resets the bucket structure.
     */
    private int compactBucket(int bucket, int bucketOffset, long cutoffTime) {
        // Temporary storage for valid entries
        long[] validHashes = new long[bucketSize];
        int[] validValue1s = new int[bucketSize];
        int[] validValue2s = new int[bucketSize];
        long[] validTimestamps = new long[bucketSize];
        int validCount = 0;
        int expiredCount = 0;

        // Collect valid, non-expired entries
        for (int i = 0; i < bucketSize; i++) {
            int offset = bucketOffset + i * ENTRY_SIZE;
            long storedHash = readLong(offset);

            if (storedHash == EMPTY_HASH || storedHash == TOMBSTONE_HASH) {
                continue;
            }

            long timestamp = readLong(offset + TIMESTAMP_OFFSET);
            if (timestamp >= cutoffTime) {
                // Keep this entry
                validHashes[validCount] = storedHash;
                validValue1s[validCount] = readInt(offset + HASH_SIZE);
                validValue2s[validCount] = readInt(offset + HASH_SIZE + INT_SIZE);
                validTimestamps[validCount] = timestamp;
                validCount++;
            } else {
                expiredCount++;
            }
        }

        // Clear the entire bucket
        int bucketBytes = bucketSize * ENTRY_SIZE;
        for (int i = 0; i < bucketBytes; i++) {
            storage[bucketOffset + i] = 0;
        }
        tombstoneCounts[bucket] = 0;

        // Re-insert valid entries using their hash to find slots
        for (int i = 0; i < validCount; i++) {
            long hash = validHashes[i];
            int startSlot = getSlotInBucket(hash);

            for (int j = 0; j < bucketSize; j++) {
                int slot = (startSlot + j) % bucketSize;
                int offset = bucketOffset + slot * ENTRY_SIZE;
                long storedHash = readLong(offset);

                if (storedHash == EMPTY_HASH) {
                    writeLong(offset, hash);
                    writeInt(offset + HASH_SIZE, validValue1s[i]);
                    writeInt(offset + HASH_SIZE + INT_SIZE, validValue2s[i]);
                    writeLong(offset + TIMESTAMP_OFFSET, validTimestamps[i]);
                    break;
                }
            }
        }

        return expiredCount;
    }

    /**
     * Returns the number of bytes used by the storage array.
     * @return storage size in bytes
     */
    public int getStorageSize() {
        return storage.length;
    }

    /**
     * Returns the total number of entries this cache can hold.
     * @return number of cache slots
     */
    public int getCapacity() {
        return numBuckets * bucketSize;
    }

    /**
     * Returns the number of buckets.
     * @return number of buckets
     */
    public int getNumBuckets() {
        return numBuckets;
    }

    /**
     * Returns the number of entries per bucket.
     * @return bucket size
     */
    public int getBucketSize() {
        return bucketSize;
    }
}
