package com.g20.CPEN431.A7;

import java.net.SocketException;

// This code was in part generated by an LLM.
public class Main {
    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("Usage: java Main <port>");
            System.exit(1);
        }

        int port = Integer.parseInt(args[0]);

        try {
            Server server = new Server(port);
            System.out.println("Server is running on port: " + port);
            server.start();
        } catch (SocketException e) {
            System.err.println("Failed to start server: " + e.getMessage());
            System.exit(1);
        }
    }
}
