package com.g20.CPEN431.A7;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;

import java.net.DatagramPacket;
import java.net.InetAddress;

// This code was in part generated by an LLM.
public class ReceivedPacket {
    public final Msg msg;
    public final InetAddress address;
    public final int port;

    public ReceivedPacket(Msg msg, DatagramPacket packet) {
        this.msg = msg;
        this.address = packet.getAddress();
        this.port = packet.getPort();
    }
}
