package com.g20.CPEN431.A7;

/**
 * A fixed-length cache that stores two integers indexed by a bytestring key.
 * Uses a single byte[] array as storage with linear probing for collisions.
 * Not thread-safe - designed for single-threaded worker use with periodic swapping.
 * Entry layout: 8 bytes hash + 1 byte generation + 4 bytes value1 + 4 bytes value2 = 17 bytes per entry.
 * Uses generation counter for O(1) wipe; recreates array on wraparound.
 */
// This code was in part generated by an LLM.
public class ResponseCache {
    private static final int ENTRY_SIZE = 17;
    private static final int HASH_SIZE = 8;
    private static final int GEN_SIZE = 1;
    private static final int INT_SIZE = 4;
    private static final int GEN_OFFSET = HASH_SIZE;
    private static final int VALUE1_OFFSET = HASH_SIZE + GEN_SIZE;
    private static final int VALUE2_OFFSET = HASH_SIZE + GEN_SIZE + INT_SIZE;

    private byte[] storage;
    private final int capacity;
    private final int maxProbes;  // Limit probing to avoid infinite loops in full cache
    private byte currentGeneration = 1;  // Start at 1; 0 in storage means empty/stale

    /**
     * Creates a cache with the specified number of entries.
     * @param capacity the number of entries the cache can hold
     */
    public ResponseCache(int capacity) {
        this.capacity = capacity;
        this.storage = new byte[capacity * ENTRY_SIZE];
        // Limit probing to avoid worst-case full scans; cap at capacity or 64
        this.maxProbes = Math.min(capacity, 64);
    }

    /**
     * Computes a 64-bit FNV-1a hash of the key.
     */
    private long computeHash(byte[] key) {
        long hash = 0xcbf29ce484222325L;
        for (byte b : key) {
            hash ^= (b & 0xff);
            hash *= 0x100000001b3L;
        }
        return hash;
    }

    /**
     * Maps a hash to a starting slot index.
     */
    private int getSlot(long hash) {
        return (int) ((hash & 0x7fffffffffffffffL) % capacity);
    }

    /**
     * Writes a long value to the storage array at the specified offset.
     */
    private void writeLong(int offset, long value) {
        storage[offset]     = (byte) (value >>> 56);
        storage[offset + 1] = (byte) (value >>> 48);
        storage[offset + 2] = (byte) (value >>> 40);
        storage[offset + 3] = (byte) (value >>> 32);
        storage[offset + 4] = (byte) (value >>> 24);
        storage[offset + 5] = (byte) (value >>> 16);
        storage[offset + 6] = (byte) (value >>> 8);
        storage[offset + 7] = (byte) value;
    }

    /**
     * Reads a long value from the storage array at the specified offset.
     */
    private long readLong(int offset) {
        return ((long) (storage[offset] & 0xff) << 56)
             | ((long) (storage[offset + 1] & 0xff) << 48)
             | ((long) (storage[offset + 2] & 0xff) << 40)
             | ((long) (storage[offset + 3] & 0xff) << 32)
             | ((long) (storage[offset + 4] & 0xff) << 24)
             | ((long) (storage[offset + 5] & 0xff) << 16)
             | ((long) (storage[offset + 6] & 0xff) << 8)
             | ((long) (storage[offset + 7] & 0xff));
    }

    /**
     * Writes an int value to the storage array at the specified offset.
     */
    private void writeInt(int offset, int value) {
        storage[offset]     = (byte) (value >>> 24);
        storage[offset + 1] = (byte) (value >>> 16);
        storage[offset + 2] = (byte) (value >>> 8);
        storage[offset + 3] = (byte) value;
    }

    /**
     * Reads an int value from the storage array at the specified offset.
     */
    private int readInt(int offset) {
        return ((storage[offset] & 0xff) << 24)
             | ((storage[offset + 1] & 0xff) << 16)
             | ((storage[offset + 2] & 0xff) << 8)
             | (storage[offset + 3] & 0xff);
    }

    /**
     * Stores two integers in the cache indexed by the given key.
     * Uses linear probing for collision resolution.
     * Stale entries (wrong generation) are treated as empty and can be overwritten.
     * @param key the bytestring key
     * @param value1 the first integer
     * @param value2 the second integer
     * @return true if stored successfully, false if cache is full (max probes exceeded)
     */
    public boolean put(byte[] key, int value1, int value2) {
        long hash = computeHash(key);
        int startSlot = getSlot(hash);

        for (int i = 0; i < maxProbes; i++) {
            int slot = (startSlot + i) % capacity;
            int offset = slot * ENTRY_SIZE;
            long storedHash = readLong(offset);
            byte storedGen = storage[offset + GEN_OFFSET];

            if (storedGen != currentGeneration) {
                // Empty or stale slot - insert here
                writeLong(offset, hash);
                storage[offset + GEN_OFFSET] = currentGeneration;
                writeInt(offset + VALUE1_OFFSET, value1);
                writeInt(offset + VALUE2_OFFSET, value2);
                return true;
            }
            if (storedHash == hash) {
                // Same key - update in place
                storage[offset + GEN_OFFSET] = currentGeneration;
                writeInt(offset + VALUE1_OFFSET, value1);
                writeInt(offset + VALUE2_OFFSET, value2);
                return true;
            }
        }

        // Max probes exceeded - cache is too full
        return false;
    }

    /**
     * Stores a single integer in the cache indexed by the given key.
     * The second integer is set to 0.
     * @param key the bytestring key
     * @param value the integer to store
     * @return true if stored successfully, false if cache is full
     */
    public boolean put(byte[] key, int value) {
        return put(key, value, 0);
    }

    /**
     * Retrieves the two integers associated with the given key.
     * Uses linear probing for collision resolution.
     * Empty/stale entries terminate search (current-gen entries form contiguous chains).
     * @param key the bytestring key
     * @return an int array of length 2 containing the values, or null if not found
     */
    public int[] get(byte[] key) {
        long hash = computeHash(key);
        int startSlot = getSlot(hash);

        for (int i = 0; i < maxProbes; i++) {
            int slot = (startSlot + i) % capacity;
            int offset = slot * ENTRY_SIZE;
            byte storedGen = storage[offset + GEN_OFFSET];

            if (storedGen != currentGeneration) {
                // Empty or stale slot - key would have been here if it existed
                return null;
            }
            long storedHash = readLong(offset);
            if (storedHash == hash) {
                // Found the key
                int value1 = readInt(offset + VALUE1_OFFSET);
                int value2 = readInt(offset + VALUE2_OFFSET);
                return new int[] { value1, value2 };
            }
        }
        // Max probes exceeded - key not found
        return null;
    }

    /**
     * Checks if there is space to store an entry for the given key.
     * Returns true if an empty/stale slot or matching hash is found within maxProbes.
     * @param key the bytestring key
     * @return true if the key can be stored, false otherwise
     */
    public boolean hasSpaceFor(byte[] key) {
        long hash = computeHash(key);
        int startSlot = getSlot(hash);

        for (int i = 0; i < maxProbes; i++) {
            int slot = (startSlot + i) % capacity;
            int offset = slot * ENTRY_SIZE;
            long storedHash = readLong(offset);
            byte storedGen = storage[offset + GEN_OFFSET];

            if (storedGen != currentGeneration || storedHash == hash) {
                return true;
            }
        }
        return false;
    }

    /**
     * Returns the number of bytes used by the storage array.
     * @return storage size in bytes
     */
    public int getStorageSize() {
        return storage.length;
    }

    /**
     * Returns the total number of entries this cache can hold.
     * @return number of cache slots
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Invalidates all entries by incrementing the generation counter.
     * O(1) operation in normal case. On wraparound (every 255 wipes),
     * allocates a new array and lets GC reclaim the old one.
     */
    public void wipe() {
        currentGeneration++;
        if (currentGeneration == 0) {
            // Wraparound: allocate fresh array, skip generation 0
            storage = new byte[capacity * ENTRY_SIZE];
            currentGeneration = 1;
        }
    }
}
