package com.g20.CPEN431.A7;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;

import static com.g20.CPEN431.A7.Constants.*;
import static com.g20.CPEN431.A7.MessageUtils.*;

// This code was in part generated by an LLM.
public class Server {
    private final DatagramSocket socket;
    private final Worker[] workers;
    private volatile boolean running = true;

    public Server(int port) throws SocketException {
        this.socket = new DatagramSocket(port);
        this.workers = new Worker[NUM_WORKERS];
        for (int i = 0; i < NUM_WORKERS; i++) {
            workers[i] = new Worker(i, this.socket);
        }
    }

    public void start() {
        for (Worker worker : workers) {
            worker.start();
        }

        byte[] buffer = new byte[MAX_PACKET_SIZE];
        DatagramPacket packet = new DatagramPacket(buffer, buffer.length);

        while (running) {
            try {
                socket.receive(packet);

                Msg msg;
                try {
                    msg = Msg.parseFrom(ByteString.copyFrom(buffer, 0, packet.getLength()));
                } catch (InvalidProtocolBufferException e) {
                    continue;
                }

                ReceivedPacket received = new ReceivedPacket(msg, packet);

                int workerIndex = Math.abs(msg.getMessageID().hashCode() % NUM_WORKERS);
                Worker worker = workers[workerIndex];

                if (!worker.offer(received)) {
                    if (!verifyChecksum(msg)) {
                        continue;
                    }
//                    System.out.println("Overload: Worker Queues too small");
                    handleOverload(received, msg.getMessageID());
                }
            } catch (IOException e) {
                if (running) {
                    e.printStackTrace();
                }
            }
        }
    }

    private void handleOverload(ReceivedPacket packet, ByteString messageId) {
        try {
            byte[] response = buildMsg(messageId, buildOverloadResponse());
            DatagramPacket responsePacket = new DatagramPacket(
                    response, response.length,
                    packet.address, packet.port
            );
            socket.send(responsePacket);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void stop() {
        running = false;
        for (Worker worker : workers) {
            worker.shutdown();
        }
        socket.close();
    }
}
