package com.g20.CPEN431.A7;

import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.util.List;

import static com.g20.CPEN431.A7.Constants.*;
import static com.g20.CPEN431.A7.MessageUtils.*;

// This code was in part generated by an LLM.
public class Server {
    private final DatagramSocket socket;
    private final Worker[] workers;
    private volatile boolean running = true;

    private final GossipService gossipService;
    private final Node selfNode;

    public Server(int port, List<Node> allNodes) throws SocketException {
        this.socket = new DatagramSocket(port);

        // Increase socket receive buffer to reduce packet drops under load
        try {
            socket.setReceiveBufferSize(4 * 1024 * 1024); // 4MB
        } catch (SocketException e) {
            // Best effort — OS may cap this
        }

        // Identify self from the node list
        this.selfNode = findSelf(allNodes, port);
        if (selfNode == null) {
            throw new RuntimeException(
                    "Could not find self in nodes list for port " + port
                            + ". Make sure the nodes file contains this node's address.");
        }
        System.out.println("Self node: id=" + selfNode.id
                + " addr=" + selfNode.ipaddress.getHostAddress() + ":" + selfNode.port);

        // Initialize consistent hash ring and gossip service
        ConsistentHashmap hashRing = new ConsistentHashmap(VIRTUAL_NODES);
        this.gossipService = new GossipService(selfNode, socket, hashRing);
        gossipService.addBootstrapNodes(allNodes);

        // Create workers, passing gossip service for routing decisions
        this.workers = new Worker[NUM_WORKERS];
        for (int i = 0; i < NUM_WORKERS; i++) {
            workers[i] = new Worker(i, this.socket, gossipService);
        }
    }

    /**
     * Find our own Node object from the list by matching port and local addresses.
     */
    private Node findSelf(List<Node> allNodes, int port) {
        try {
            InetAddress localAddr = InetAddress.getLocalHost();
            String localHostname = localAddr.getHostName();
            String localIp = localAddr.getHostAddress();

            for (Node node : allNodes) {
                if (node.port != port) continue;

                String nodeIp = node.ipaddress.getHostAddress();
                String nodeHostname = node.ipaddress.getHostName();

                // Match by IP, hostname, or loopback
                if (nodeIp.equals(localIp)
                        || nodeHostname.equals(localHostname)
                        || node.ipaddress.isLoopbackAddress()
                        || nodeIp.equals("127.0.0.1")
                        || nodeIp.equals("0.0.0.0")) {
                    return node;
                }
            }

            // Fallback: if running locally with multiple processes, match by port only
            // and pick the first node with this port
            for (Node node : allNodes) {
                if (node.port == port) {
                    return node;
                }
            }
        } catch (Exception e) {
            System.err.println("Error finding self node: " + e.getMessage());
        }
        return null;
    }

    public void start() {
        // Start gossip service
        gossipService.start();

        // Start worker threads
        for (Worker worker : workers) {
            worker.start();
        }

        byte[] buffer = new byte[MAX_PACKET_SIZE];
        DatagramPacket packet = new DatagramPacket(buffer, buffer.length);

        while (running) {
            try {
                socket.receive(packet);

                // Check if this is a gossip message (internal protocol)
                if (GossipMessage.isGossipMessage(buffer, packet.getLength())) {
                    handleGossipPacket(buffer, packet);
                    continue;
                }

                // Check if this is a forwarded message (from another node)
                boolean isForwarded = isForwardedMessage(buffer, packet.getLength());
                int msgOffset = isForwarded ? FORWARD_MAGIC.length : 0;

                // Parse protobuf (skip forward magic prefix if present)
                Msg msg;
                try {
                    msg = Msg.parseFrom(ByteString.copyFrom(
                            buffer, msgOffset, packet.getLength() - msgOffset));
                } catch (InvalidProtocolBufferException e) {
                    continue;
                }

                ReceivedPacket received = new ReceivedPacket(msg, packet, isForwarded);

                int workerIndex = Math.abs(msg.getMessageID().hashCode() % NUM_WORKERS);
                Worker worker = workers[workerIndex];

                if (!worker.offer(received)) {
                    if (!verifyChecksum(msg)) {
                        continue;
                    }
                    handleOverload(received, msg.getMessageID());
                }
            } catch (IOException e) {
                if (running) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * Handle an incoming gossip packet on the server receive thread.
     */
    private void handleGossipPacket(byte[] buffer, DatagramPacket packet) {
        try {
            GossipMessage msg = GossipMessage.deserialize(buffer, packet.getLength());
            if (msg != null) {
                gossipService.handleGossipMessage(msg, packet.getAddress(), packet.getPort());
            }
        } catch (Exception e) {
            System.err.println("Error handling gossip packet: " + e.getMessage());
        }
    }

    private void handleOverload(ReceivedPacket packet, ByteString messageId) {
        try {
            byte[] response = buildMsg(messageId, buildOverloadResponse());
            DatagramPacket responsePacket = new DatagramPacket(
                    response, response.length,
                    packet.address, packet.port
            );
            socket.send(responsePacket);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Check if a packet starts with the forwarding magic prefix.
     */
    private static boolean isForwardedMessage(byte[] data, int length) {
        if (length < FORWARD_MAGIC.length) return false;
        return data[0] == FORWARD_MAGIC[0]
                && data[1] == FORWARD_MAGIC[1]
                && data[2] == FORWARD_MAGIC[2]
                && data[3] == FORWARD_MAGIC[3];
    }

    public void stop() {
        running = false;
        gossipService.stop();
        Worker.shutdownForwardPool();
        for (Worker worker : workers) {
            worker.shutdown();
        }
        socket.close();
    }
}