package com.g20.CPEN431.A7;

import ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest;
import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.concurrent.ArrayBlockingQueue;

import static com.g20.CPEN431.A7.Constants.*;
import static com.g20.CPEN431.A7.MessageUtils.*;

// This code was in part generated by an LLM.
public class Worker extends Thread {
    private final ArrayBlockingQueue<ReceivedPacket> queue;
    private final DualResponseCache cache;
    private final DatagramSocket sendSocket;
    private volatile boolean running = true;

    public Worker(int id, DatagramSocket socket) throws SocketException {
        super("Worker-" + id);
        this.queue = new ArrayBlockingQueue<>(QUEUE_SIZE_PER_WORKER);
        this.cache = new DualResponseCache(MAX_CACHE_ENTRIES_PER_WORKER / 2, CACHE_CLEANUP_INTERVAL_MS);
        this.sendSocket = socket;
    }

    public boolean offer(ReceivedPacket packet) {
        return queue.offer(packet);
    }

    public void shutdown() {
        running = false;
        this.interrupt();
        sendSocket.close();
    }

    @Override
    public void run() {
        while (running) {
            try {
                ReceivedPacket packet = queue.take();
                handleRequest(packet);
            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void handleRequest(ReceivedPacket packet) {
        try {
            Msg msg = packet.msg;

            if (!verifyChecksum(msg)) {
                return;
            }

            ByteString messageId = msg.getMessageID();
            byte[] messageIdBytes = messageId.toByteArray();

            KVRequest request;
            try {
                request = KVRequest.parseFrom(msg.getPayload());
            } catch (InvalidProtocolBufferException e) {
                byte[] errorResponse = buildMsg(messageId, buildKVResponse(ERR_INTERNAL_FAILURE));
                sendResponse(packet, errorResponse);
                return;
            }

            int command = request.getCommand();

            if (isMutableCommand(command)) {
                // Check cache for duplicate request
                KVResponse cachedResponse = cache.getResponse(messageIdBytes, command);
                if (cachedResponse != null) {
                    sendResponse(packet, buildMsg(messageId, cachedResponse));
                    return;
                }

                // Check if there's space to cache before processing
                if (!cache.hasSpaceFor(messageIdBytes)) {
//                    System.out.println("Overload: Cache too small");
                    sendResponse(packet, buildMsg(messageId, buildOverloadResponse()));
                    return;
                }

                // Process request
                KVResponse response = RequestHandler.processRequest(request);

                // Cache the response
                cache.put(messageIdBytes, response);

                sendResponse(packet, buildMsg(messageId, response));
            } else {
                KVResponse response = RequestHandler.processRequest(request);
                sendResponse(packet, buildMsg(messageId, response));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void sendResponse(ReceivedPacket packet, byte[] response) throws IOException {
        DatagramPacket responsePacket = new DatagramPacket(
                response, response.length,
                packet.address, packet.port
        );
        sendSocket.send(responsePacket);
    }
}
