package com.g20.CPEN431.A7;

import ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest;
import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.concurrent.ArrayBlockingQueue;

import static com.g20.CPEN431.A7.Constants.*;
import static com.g20.CPEN431.A7.MessageUtils.*;

// This code was in part generated by an LLM.
public class Worker extends Thread {
    private final ArrayBlockingQueue<ReceivedPacket> queue;
    private final DualResponseCache cache;
    private final DatagramSocket sendSocket;
    private final GossipService gossipService;
    private volatile boolean running = true;

    public Worker(int id, DatagramSocket socket, GossipService gossipService) throws SocketException {
        super("Worker-" + id);
        this.queue = new ArrayBlockingQueue<>(QUEUE_SIZE_PER_WORKER);
        this.cache = new DualResponseCache(MAX_CACHE_ENTRIES_PER_WORKER / 2, CACHE_CLEANUP_INTERVAL_MS);
        this.sendSocket = socket;
        this.gossipService = gossipService;
    }

    public boolean offer(ReceivedPacket packet) {
        return queue.offer(packet);
    }

    public void shutdown() {
        running = false;
        this.interrupt();
        sendSocket.close();
    }

    @Override
    public void run() {
        while (running) {
            try {
                ReceivedPacket packet = queue.take();
                handleRequest(packet);
            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void handleRequest(ReceivedPacket packet) {
        try {
            Msg msg = packet.msg;

            if (!verifyChecksum(msg)) {
                return;
            }

            ByteString messageId = msg.getMessageID();
            byte[] messageIdBytes = messageId.toByteArray();

            KVRequest request;
            try {
                request = KVRequest.parseFrom(msg.getPayload());
            } catch (InvalidProtocolBufferException e) {
                byte[] errorResponse = buildMsg(messageId, buildKVResponse(ERR_INTERNAL_FAILURE));
                sendResponse(packet, errorResponse);
                return;
            }

            int command = request.getCommand();

            // Commands that are always handled locally (node-specific)
            if (command == CMD_SHUTDOWN || command == CMD_WIPEOUT
                    || command == CMD_IS_ALIVE || command == CMD_GET_PID
                    || command == CMD_GET_MEMBERSHIP_COUNT) {
                processLocally(packet, msg, request, command, messageId, messageIdBytes);
                return;
            }

            // For PUT, GET, REMOVE: check if we own this key
            if (request.hasKey() && !request.getKey().isEmpty()) {
                Node responsible = gossipService.getHashRing().getNodeForKey(request.getKey());

                if (responsible != null && responsible.id != gossipService.getSelfNode().id) {
                    // Forward to the responsible node
                    forwardRequest(packet, msg, request, command, messageId, messageIdBytes, responsible);
                    return;
                }
            }

            // We own this key (or no key provided) - process locally
            processLocally(packet, msg, request, command, messageId, messageIdBytes);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Process a request locally using the existing logic.
     */
    private void processLocally(ReceivedPacket packet, Msg msg, KVRequest request,
                                int command, ByteString messageId, byte[] messageIdBytes) throws IOException {
        if (isMutableCommand(command)) {
            // Check cache for duplicate request
            KVResponse cachedResponse = cache.getResponse(messageIdBytes, command);
            if (cachedResponse != null) {
                sendResponse(packet, buildMsg(messageId, cachedResponse));
                return;
            }

            // Check if there's space to cache before processing
            if (!cache.hasSpaceFor(messageIdBytes)) {
                sendResponse(packet, buildMsg(messageId, buildOverloadResponse()));
                return;
            }

            // Process request
            KVResponse response = RequestHandler.processRequest(request, gossipService);

            // Cache the response
            cache.put(messageIdBytes, response);

            sendResponse(packet, buildMsg(messageId, response));
        } else {
            KVResponse response = RequestHandler.processRequest(request, gossipService);
            sendResponse(packet, buildMsg(messageId, response));
        }
    }

    /**
     * Forward a client request to the responsible node and relay the response back.
     * Uses a fresh ephemeral socket per forward to avoid response mixups between
     * concurrent forwarded requests. On failure, falls back to returning an error
     * so the client can retry.
     */
    private void forwardRequest(ReceivedPacket originalPacket, Msg originalMsg,
                                KVRequest request, int command,
                                ByteString messageId, byte[] messageIdBytes,
                                Node target) {
        DatagramSocket fwdSocket = null;
        try {
            // Create a fresh socket for this specific forward to avoid response mixups
            fwdSocket = new DatagramSocket();
            fwdSocket.setSoTimeout(FORWARD_TIMEOUT_MS);

            // Send the original serialized message to the target node
            byte[] msgBytes = originalMsg.toByteArray();
            DatagramPacket forwardPacket = new DatagramPacket(
                    msgBytes, msgBytes.length,
                    target.ipaddress, target.port
            );
            fwdSocket.send(forwardPacket);

            // Wait for response from target, with message ID validation
            byte[] responseBuf = new byte[MAX_PACKET_SIZE];
            DatagramPacket responsePacket = new DatagramPacket(responseBuf, responseBuf.length);

            // Retry loop: keep receiving until we get the matching response or timeout
            long deadline = System.currentTimeMillis() + FORWARD_TIMEOUT_MS;
            while (System.currentTimeMillis() < deadline) {
                int remaining = (int) (deadline - System.currentTimeMillis());
                if (remaining <= 0) break;
                fwdSocket.setSoTimeout(remaining);

                fwdSocket.receive(responsePacket);

                // Validate the response matches our request's message ID
                try {
                    Msg responseMsg = Msg.parseFrom(
                            ByteString.copyFrom(responseBuf, 0, responsePacket.getLength()));

                    if (responseMsg.getMessageID().equals(messageId)) {
                        // Matching response - relay back to the original client
                        DatagramPacket clientResponse = new DatagramPacket(
                                responseBuf, responsePacket.getLength(),
                                originalPacket.address, originalPacket.port
                        );
                        sendSocket.send(clientResponse);
                        return; // Success
                    }
                    // Non-matching message ID - discard and keep waiting
                } catch (InvalidProtocolBufferException e) {
                    // Couldn't parse response - discard and keep waiting
                }
            }

            // Timed out waiting for a matching response - send error to client
            sendErrorToClient(originalPacket, messageId);

        } catch (java.net.SocketTimeoutException e) {
            // Forward timed out - send error so client can retry
            sendErrorToClient(originalPacket, messageId);
        } catch (IOException e) {
            // Forward failed - send error so client can retry
            System.err.println("Forward failed to node " + target.id + ": " + e.getMessage());
            sendErrorToClient(originalPacket, messageId);
        } finally {
            if (fwdSocket != null && !fwdSocket.isClosed()) {
                fwdSocket.close();
            }
        }
    }

    /**
     * Send an overload/retry error back to the client when forwarding fails.
     * This ensures the client gets a response and can retry, rather than
     * silently dropping the request.
     */
    private void sendErrorToClient(ReceivedPacket originalPacket, ByteString messageId) {
        try {
            byte[] response = buildMsg(messageId, buildOverloadResponse());
            DatagramPacket responsePacket = new DatagramPacket(
                    response, response.length,
                    originalPacket.address, originalPacket.port
            );
            sendSocket.send(responsePacket);
        } catch (IOException ex) {
            // Best effort - nothing more we can do
        }
    }

    private void sendResponse(ReceivedPacket packet, byte[] response) throws IOException {
        DatagramPacket responsePacket = new DatagramPacket(
                response, response.length,
                packet.address, packet.port
        );
        sendSocket.send(responsePacket);
    }
}