package com.g20.CPEN431.A7;

import ca.NetSysLab.ProtocolBuffers.KeyValueRequest.KVRequest;
import ca.NetSysLab.ProtocolBuffers.KeyValueResponse.KVResponse;
import ca.NetSysLab.ProtocolBuffers.Message.Msg;
import com.google.protobuf.ByteString;
import com.google.protobuf.InvalidProtocolBufferException;

import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.SocketException;
import java.util.concurrent.ArrayBlockingQueue;

import static com.g20.CPEN431.A7.Constants.*;
import static com.g20.CPEN431.A7.MessageUtils.*;

// This code was in part generated by an LLM.
public class Worker extends Thread {
    private final ArrayBlockingQueue<ReceivedPacket> queue;
    private final DualResponseCache cache;
    private final DatagramSocket sendSocket;
    private final GossipService gossipService;
    private volatile boolean running = true;

    // Dedicated socket for forwarding requests (so we can set a timeout)
    private DatagramSocket forwardSocket;

    public Worker(int id, DatagramSocket socket, GossipService gossipService) throws SocketException {
        super("Worker-" + id);
        this.queue = new ArrayBlockingQueue<>(QUEUE_SIZE_PER_WORKER);
        this.cache = new DualResponseCache(MAX_CACHE_ENTRIES_PER_WORKER / 2, CACHE_CLEANUP_INTERVAL_MS);
        this.sendSocket = socket;
        this.gossipService = gossipService;

        // Create a separate socket for forwarding with timeout
        this.forwardSocket = new DatagramSocket();
        this.forwardSocket.setSoTimeout(FORWARD_TIMEOUT_MS);
    }

    public boolean offer(ReceivedPacket packet) {
        return queue.offer(packet);
    }

    public void shutdown() {
        running = false;
        this.interrupt();
        if (forwardSocket != null && !forwardSocket.isClosed()) {
            forwardSocket.close();
        }
        sendSocket.close();
    }

    @Override
    public void run() {
        while (running) {
            try {
                ReceivedPacket packet = queue.take();
                handleRequest(packet);
            } catch (InterruptedException e) {
                if (!running) break;
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void handleRequest(ReceivedPacket packet) {
        try {
            Msg msg = packet.msg;

            if (!verifyChecksum(msg)) {
                return;
            }

            ByteString messageId = msg.getMessageID();
            byte[] messageIdBytes = messageId.toByteArray();

            KVRequest request;
            try {
                request = KVRequest.parseFrom(msg.getPayload());
            } catch (InvalidProtocolBufferException e) {
                byte[] errorResponse = buildMsg(messageId, buildKVResponse(ERR_INTERNAL_FAILURE));
                sendResponse(packet, errorResponse);
                return;
            }

            int command = request.getCommand();

            // Commands that are always handled locally (node-specific)
            if (command == CMD_SHUTDOWN || command == CMD_WIPEOUT
                    || command == CMD_IS_ALIVE || command == CMD_GET_PID
                    || command == CMD_GET_MEMBERSHIP_COUNT) {
                processLocally(packet, msg, request, command, messageId, messageIdBytes);
                return;
            }

            // For PUT, GET, REMOVE: check if we own this key
            if (request.hasKey() && !request.getKey().isEmpty()) {
                Node responsible = gossipService.getHashRing().getNodeForKey(request.getKey());

                if (responsible != null && responsible.id != gossipService.getSelfNode().id) {
                    // Forward to the responsible node
                    forwardRequest(packet, msg, responsible);
                    return;
                }
            }

            // We own this key (or no key provided) - process locally
            processLocally(packet, msg, request, command, messageId, messageIdBytes);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Process a request locally using the existing logic.
     */
    private void processLocally(ReceivedPacket packet, Msg msg, KVRequest request,
                                int command, ByteString messageId, byte[] messageIdBytes) throws IOException {
        if (isMutableCommand(command)) {
            // Check cache for duplicate request
            KVResponse cachedResponse = cache.getResponse(messageIdBytes, command);
            if (cachedResponse != null) {
                sendResponse(packet, buildMsg(messageId, cachedResponse));
                return;
            }

            // Check if there's space to cache before processing
            if (!cache.hasSpaceFor(messageIdBytes)) {
                sendResponse(packet, buildMsg(messageId, buildOverloadResponse()));
                return;
            }

            // Process request
            KVResponse response = RequestHandler.processRequest(request, gossipService);

            // Cache the response
            cache.put(messageIdBytes, response);

            sendResponse(packet, buildMsg(messageId, response));
        } else {
            KVResponse response = RequestHandler.processRequest(request, gossipService);
            sendResponse(packet, buildMsg(messageId, response));
        }
    }

    /**
     * Forward a client request to the responsible node and relay the response back.
     * If forwarding fails (timeout, error), return an error to the client so it can retry.
     */
    private void forwardRequest(ReceivedPacket originalPacket, Msg originalMsg, Node target) {
        try {
            // Send the original serialized message to the target node
            byte[] msgBytes = originalMsg.toByteArray();
            DatagramPacket forwardPacket = new DatagramPacket(
                    msgBytes, msgBytes.length,
                    target.ipaddress, target.port
            );
            forwardSocket.send(forwardPacket);

            // Wait for response from target
            byte[] responseBuf = new byte[MAX_PACKET_SIZE];
            DatagramPacket responsePacket = new DatagramPacket(responseBuf, responseBuf.length);
            forwardSocket.receive(responsePacket);

            // Relay response back to the original client
            DatagramPacket clientResponse = new DatagramPacket(
                    responseBuf, responsePacket.getLength(),
                    originalPacket.address, originalPacket.port
            );
            sendSocket.send(clientResponse);

        } catch (java.net.SocketTimeoutException e) {
            // Forward timed out - the target node might be down
            // Let the client retry (don't send error, client will timeout and retry)
        } catch (IOException e) {
            // Forward failed
            System.err.println("Forward failed to node " + target.id + ": " + e.getMessage());
        }
    }

    private void sendResponse(ReceivedPacket packet, byte[] response) throws IOException {
        DatagramPacket responsePacket = new DatagramPacket(
                response, response.length,
                packet.address, packet.port
        );
        sendSocket.send(responsePacket);
    }
}